// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ALUExeUnit(
  input         clock,
                reset,
                io_req_valid,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [6:0]  io_req_bits_uop_uopc,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [9:0]  io_req_bits_uop_fu_code,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input         io_req_bits_uop_ctrl_is_load,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_req_bits_uop_ctrl_is_sta,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_req_bits_uop_ctrl_is_std,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [7:0]  io_req_bits_uop_br_mask,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [19:0] io_req_bits_uop_imm_packed,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [3:0]  io_req_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [2:0]  io_req_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_req_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [5:0]  io_req_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [4:0]  io_req_bits_uop_mem_cmd,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [1:0]  io_req_bits_uop_mem_size,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input         io_req_bits_uop_mem_signed,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_req_bits_uop_is_fence,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_req_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_req_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_req_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_req_bits_uop_fp_val,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [64:0] io_req_bits_rs1_data,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_req_bits_rs2_data,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output        io_ll_iresp_valid,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [3:0]  io_ll_iresp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [5:0]  io_ll_iresp_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output        io_ll_iresp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_ll_iresp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [1:0]  io_ll_iresp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [64:0] io_ll_iresp_bits_data,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output        io_ll_fresp_valid,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [6:0]  io_ll_fresp_bits_uop_uopc,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [7:0]  io_ll_fresp_bits_uop_br_mask,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [3:0]  io_ll_fresp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [2:0]  io_ll_fresp_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [5:0]  io_ll_fresp_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [1:0]  io_ll_fresp_bits_uop_mem_size,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output        io_ll_fresp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_ll_fresp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [1:0]  io_ll_fresp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output        io_ll_fresp_bits_uop_fp_val,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [64:0] io_ll_fresp_bits_data,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [7:0]  io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_brupdate_b1_mispredict_mask,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output        io_lsu_io_req_valid,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_uop_ctrl_is_load,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_uop_ctrl_is_sta,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_uop_ctrl_is_std,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [7:0]  io_lsu_io_req_bits_uop_br_mask,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [3:0]  io_lsu_io_req_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [2:0]  io_lsu_io_req_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [5:0]  io_lsu_io_req_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [4:0]  io_lsu_io_req_bits_uop_mem_cmd,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [1:0]  io_lsu_io_req_bits_uop_mem_size,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output        io_lsu_io_req_bits_uop_mem_signed,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_uop_is_fence,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_uop_fp_val,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [63:0] io_lsu_io_req_bits_data,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [39:0] io_lsu_io_req_bits_addr,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output        io_lsu_io_req_bits_mxcpt_valid,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_sfence_valid,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_sfence_bits_rs1,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_req_bits_sfence_bits_rs2,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  output [38:0] io_lsu_io_req_bits_sfence_bits_addr,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input         io_lsu_io_iresp_valid,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [3:0]  io_lsu_io_iresp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [5:0]  io_lsu_io_iresp_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input         io_lsu_io_iresp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_iresp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [1:0]  io_lsu_io_iresp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [63:0] io_lsu_io_iresp_bits_data,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input         io_lsu_io_fresp_valid,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [6:0]  io_lsu_io_fresp_bits_uop_uopc,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [7:0]  io_lsu_io_fresp_bits_uop_br_mask,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [3:0]  io_lsu_io_fresp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [2:0]  io_lsu_io_fresp_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [5:0]  io_lsu_io_fresp_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [1:0]  io_lsu_io_fresp_bits_uop_mem_size,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input         io_lsu_io_fresp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
                io_lsu_io_fresp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [1:0]  io_lsu_io_fresp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input         io_lsu_io_fresp_bits_uop_fp_val,	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
  input  [64:0] io_lsu_io_fresp_bits_data	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:106:14]
);

  wire [64:0] _maddrcalc_io_resp_bits_data;	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:393:27]
  MemAddrCalcUnit maddrcalc (	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:393:27]
    .clock                          (clock),
    .reset                          (reset),
    .io_req_valid                   (io_req_valid & io_req_bits_uop_fu_code[2]),	// @[generators/boom/src/main/scala/common/micro-op.scala:154:40, generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:395:45]
    .io_req_bits_uop_uopc           (io_req_bits_uop_uopc),
    .io_req_bits_uop_ctrl_is_load   (io_req_bits_uop_ctrl_is_load),
    .io_req_bits_uop_ctrl_is_sta    (io_req_bits_uop_ctrl_is_sta),
    .io_req_bits_uop_ctrl_is_std    (io_req_bits_uop_ctrl_is_std),
    .io_req_bits_uop_br_mask        (io_req_bits_uop_br_mask),
    .io_req_bits_uop_imm_packed     (io_req_bits_uop_imm_packed),
    .io_req_bits_uop_rob_idx        (io_req_bits_uop_rob_idx),
    .io_req_bits_uop_ldq_idx        (io_req_bits_uop_ldq_idx),
    .io_req_bits_uop_stq_idx        (io_req_bits_uop_stq_idx),
    .io_req_bits_uop_pdst           (io_req_bits_uop_pdst),
    .io_req_bits_uop_mem_cmd        (io_req_bits_uop_mem_cmd),
    .io_req_bits_uop_mem_size       (io_req_bits_uop_mem_size),
    .io_req_bits_uop_mem_signed     (io_req_bits_uop_mem_signed),
    .io_req_bits_uop_is_fence       (io_req_bits_uop_is_fence),
    .io_req_bits_uop_is_amo         (io_req_bits_uop_is_amo),
    .io_req_bits_uop_uses_ldq       (io_req_bits_uop_uses_ldq),
    .io_req_bits_uop_uses_stq       (io_req_bits_uop_uses_stq),
    .io_req_bits_uop_fp_val         (io_req_bits_uop_fp_val),
    .io_req_bits_rs1_data           (io_req_bits_rs1_data),
    .io_req_bits_rs2_data           (io_req_bits_rs2_data),
    .io_resp_valid                  (io_lsu_io_req_valid),
    .io_resp_bits_uop_ctrl_is_load  (io_lsu_io_req_bits_uop_ctrl_is_load),
    .io_resp_bits_uop_ctrl_is_sta   (io_lsu_io_req_bits_uop_ctrl_is_sta),
    .io_resp_bits_uop_ctrl_is_std   (io_lsu_io_req_bits_uop_ctrl_is_std),
    .io_resp_bits_uop_br_mask       (io_lsu_io_req_bits_uop_br_mask),
    .io_resp_bits_uop_rob_idx       (io_lsu_io_req_bits_uop_rob_idx),
    .io_resp_bits_uop_ldq_idx       (io_lsu_io_req_bits_uop_ldq_idx),
    .io_resp_bits_uop_stq_idx       (io_lsu_io_req_bits_uop_stq_idx),
    .io_resp_bits_uop_pdst          (io_lsu_io_req_bits_uop_pdst),
    .io_resp_bits_uop_mem_cmd       (io_lsu_io_req_bits_uop_mem_cmd),
    .io_resp_bits_uop_mem_size      (io_lsu_io_req_bits_uop_mem_size),
    .io_resp_bits_uop_mem_signed    (io_lsu_io_req_bits_uop_mem_signed),
    .io_resp_bits_uop_is_fence      (io_lsu_io_req_bits_uop_is_fence),
    .io_resp_bits_uop_is_amo        (io_lsu_io_req_bits_uop_is_amo),
    .io_resp_bits_uop_uses_ldq      (io_lsu_io_req_bits_uop_uses_ldq),
    .io_resp_bits_uop_uses_stq      (io_lsu_io_req_bits_uop_uses_stq),
    .io_resp_bits_uop_fp_val        (io_lsu_io_req_bits_uop_fp_val),
    .io_resp_bits_data              (_maddrcalc_io_resp_bits_data),
    .io_resp_bits_addr              (io_lsu_io_req_bits_addr),
    .io_resp_bits_mxcpt_valid       (io_lsu_io_req_bits_mxcpt_valid),
    .io_resp_bits_sfence_valid      (io_lsu_io_req_bits_sfence_valid),
    .io_resp_bits_sfence_bits_rs1   (io_lsu_io_req_bits_sfence_bits_rs1),
    .io_resp_bits_sfence_bits_rs2   (io_lsu_io_req_bits_sfence_bits_rs2),
    .io_resp_bits_sfence_bits_addr  (io_lsu_io_req_bits_sfence_bits_addr),
    .io_brupdate_b1_resolve_mask    (io_brupdate_b1_resolve_mask),
    .io_brupdate_b1_mispredict_mask (io_brupdate_b1_mispredict_mask)
  );
  assign io_ll_iresp_valid = io_lsu_io_iresp_valid;
  assign io_ll_iresp_bits_uop_rob_idx = io_lsu_io_iresp_bits_uop_rob_idx;
  assign io_ll_iresp_bits_uop_pdst = io_lsu_io_iresp_bits_uop_pdst;
  assign io_ll_iresp_bits_uop_is_amo = io_lsu_io_iresp_bits_uop_is_amo;
  assign io_ll_iresp_bits_uop_uses_stq = io_lsu_io_iresp_bits_uop_uses_stq;
  assign io_ll_iresp_bits_uop_dst_rtype = io_lsu_io_iresp_bits_uop_dst_rtype;
  assign io_ll_iresp_bits_data = {1'h0, io_lsu_io_iresp_bits_data};	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:406:17]
  assign io_ll_fresp_valid = io_lsu_io_fresp_valid;
  assign io_ll_fresp_bits_uop_uopc = io_lsu_io_fresp_bits_uop_uopc;
  assign io_ll_fresp_bits_uop_br_mask = io_lsu_io_fresp_bits_uop_br_mask;
  assign io_ll_fresp_bits_uop_rob_idx = io_lsu_io_fresp_bits_uop_rob_idx;
  assign io_ll_fresp_bits_uop_stq_idx = io_lsu_io_fresp_bits_uop_stq_idx;
  assign io_ll_fresp_bits_uop_pdst = io_lsu_io_fresp_bits_uop_pdst;
  assign io_ll_fresp_bits_uop_mem_size = io_lsu_io_fresp_bits_uop_mem_size;
  assign io_ll_fresp_bits_uop_is_amo = io_lsu_io_fresp_bits_uop_is_amo;
  assign io_ll_fresp_bits_uop_uses_stq = io_lsu_io_fresp_bits_uop_uses_stq;
  assign io_ll_fresp_bits_uop_dst_rtype = io_lsu_io_fresp_bits_uop_dst_rtype;
  assign io_ll_fresp_bits_uop_fp_val = io_lsu_io_fresp_bits_uop_fp_val;
  assign io_ll_fresp_bits_data = io_lsu_io_fresp_bits_data;
  assign io_lsu_io_req_bits_data = _maddrcalc_io_resp_bits_data[63:0];	// @[generators/boom/src/main/scala/exu/execution-units/execution-unit.scala:393:27, :404:19]
endmodule

