// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module Arbiter_12(
  input        io_in_0_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:134:14]
  input  [6:0] io_in_0_bits_req_0_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:134:14]
  output       io_in_1_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:134:14]
  input        io_in_1_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:134:14]
  input  [6:0] io_in_1_bits_req_0_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:134:14]
  output       io_in_2_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:134:14]
  input  [6:0] io_in_2_bits_req_0_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:134:14]
  output [6:0] io_out_bits_req_0_addr	// @[src/main/scala/chisel3/util/Arbiter.scala:134:14]
);

  assign io_in_1_ready = ~io_in_0_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:45:78]
  assign io_in_2_ready = ~(io_in_0_valid | io_in_1_valid);	// @[src/main/scala/chisel3/util/Arbiter.scala:45:{68,78}]
  assign io_out_bits_req_0_addr = io_in_0_valid ? io_in_0_bits_req_0_addr : io_in_1_valid ? io_in_1_bits_req_0_addr : io_in_2_bits_req_0_addr;	// @[src/main/scala/chisel3/util/Arbiter.scala:137:15, :139:26, :141:19]
endmodule

