// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BasicDispatcher(
  output        io_ren_uops_0_ready,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_valid,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [6:0]  io_ren_uops_0_bits_uopc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [31:0] io_ren_uops_0_bits_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_debug_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_bits_is_rvc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [39:0] io_ren_uops_0_bits_debug_pc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [2:0]  io_ren_uops_0_bits_iq_type,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [9:0]  io_ren_uops_0_bits_fu_code,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_bits_is_br,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_is_jalr,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_is_jal,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_is_sfb,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [7:0]  io_ren_uops_0_bits_br_mask,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [2:0]  io_ren_uops_0_bits_br_tag,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [3:0]  io_ren_uops_0_bits_ftq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_bits_edge_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [5:0]  io_ren_uops_0_bits_pc_lob,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_bits_taken,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [19:0] io_ren_uops_0_bits_imm_packed,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [11:0] io_ren_uops_0_bits_csr_addr,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [3:0]  io_ren_uops_0_bits_rob_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [2:0]  io_ren_uops_0_bits_ldq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_stq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [1:0]  io_ren_uops_0_bits_rxq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [5:0]  io_ren_uops_0_bits_pdst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_prs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_prs2,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_prs3,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_bits_prs1_busy,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_prs2_busy,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_prs3_busy,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [5:0]  io_ren_uops_0_bits_stale_pdst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_bits_exception,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [63:0] io_ren_uops_0_bits_exc_cause,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_bits_bypassable,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [4:0]  io_ren_uops_0_bits_mem_cmd,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [1:0]  io_ren_uops_0_bits_mem_size,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_bits_mem_signed,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_is_fence,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_is_fencei,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_is_amo,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_uses_ldq,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_uses_stq,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_is_sys_pc2epc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_is_unique,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_flush_on_commit,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_ldst_is_rs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [5:0]  io_ren_uops_0_bits_ldst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_lrs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_lrs2,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_lrs3,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_bits_ldst_val,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [1:0]  io_ren_uops_0_bits_dst_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_lrs1_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_lrs2_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_ren_uops_0_bits_frs3_en,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_fp_val,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_fp_single,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_xcpt_pf_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_xcpt_ae_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_xcpt_ma_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_bp_debug_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_bp_xcpt_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input  [1:0]  io_ren_uops_0_bits_debug_fsrc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_ren_uops_0_bits_debug_tsrc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_dis_uops_2_0_ready,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_valid,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [6:0]  io_dis_uops_2_0_bits_uopc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [31:0] io_dis_uops_2_0_bits_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_debug_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_bits_is_rvc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [39:0] io_dis_uops_2_0_bits_debug_pc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [2:0]  io_dis_uops_2_0_bits_iq_type,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [9:0]  io_dis_uops_2_0_bits_fu_code,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_bits_is_br,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_is_jalr,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_is_jal,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_is_sfb,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [7:0]  io_dis_uops_2_0_bits_br_mask,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [2:0]  io_dis_uops_2_0_bits_br_tag,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [3:0]  io_dis_uops_2_0_bits_ftq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_bits_edge_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_2_0_bits_pc_lob,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_bits_taken,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [19:0] io_dis_uops_2_0_bits_imm_packed,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [11:0] io_dis_uops_2_0_bits_csr_addr,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [3:0]  io_dis_uops_2_0_bits_rob_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [2:0]  io_dis_uops_2_0_bits_ldq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_stq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_2_0_bits_rxq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_2_0_bits_pdst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_prs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_prs2,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_prs3,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_bits_prs1_busy,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_prs2_busy,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_prs3_busy,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_2_0_bits_stale_pdst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_bits_exception,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [63:0] io_dis_uops_2_0_bits_exc_cause,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_bits_bypassable,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [4:0]  io_dis_uops_2_0_bits_mem_cmd,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_2_0_bits_mem_size,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_bits_mem_signed,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_is_fence,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_is_fencei,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_is_amo,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_uses_ldq,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_uses_stq,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_is_sys_pc2epc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_is_unique,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_flush_on_commit,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_ldst_is_rs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_2_0_bits_ldst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_lrs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_lrs2,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_lrs3,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_bits_ldst_val,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_2_0_bits_dst_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_lrs1_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_lrs2_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_2_0_bits_frs3_en,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_fp_val,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_fp_single,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_xcpt_pf_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_xcpt_ae_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_xcpt_ma_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_bp_debug_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_bp_xcpt_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_2_0_bits_debug_fsrc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_2_0_bits_debug_tsrc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_dis_uops_1_0_ready,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_valid,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [6:0]  io_dis_uops_1_0_bits_uopc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [31:0] io_dis_uops_1_0_bits_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_debug_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_bits_is_rvc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [39:0] io_dis_uops_1_0_bits_debug_pc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [2:0]  io_dis_uops_1_0_bits_iq_type,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [9:0]  io_dis_uops_1_0_bits_fu_code,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_bits_is_br,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_is_jalr,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_is_jal,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_is_sfb,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [7:0]  io_dis_uops_1_0_bits_br_mask,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [2:0]  io_dis_uops_1_0_bits_br_tag,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [3:0]  io_dis_uops_1_0_bits_ftq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_bits_edge_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_1_0_bits_pc_lob,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_bits_taken,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [19:0] io_dis_uops_1_0_bits_imm_packed,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [11:0] io_dis_uops_1_0_bits_csr_addr,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [3:0]  io_dis_uops_1_0_bits_rob_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [2:0]  io_dis_uops_1_0_bits_ldq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_stq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_1_0_bits_rxq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_1_0_bits_pdst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_prs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_prs2,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_prs3,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_bits_prs1_busy,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_prs2_busy,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_1_0_bits_stale_pdst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_bits_exception,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [63:0] io_dis_uops_1_0_bits_exc_cause,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_bits_bypassable,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [4:0]  io_dis_uops_1_0_bits_mem_cmd,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_1_0_bits_mem_size,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_bits_mem_signed,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_is_fence,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_is_fencei,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_is_amo,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_uses_ldq,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_uses_stq,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_is_sys_pc2epc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_is_unique,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_flush_on_commit,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_ldst_is_rs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_1_0_bits_ldst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_lrs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_lrs2,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_lrs3,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_bits_ldst_val,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_1_0_bits_dst_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_lrs1_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_lrs2_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_1_0_bits_frs3_en,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_fp_val,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_fp_single,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_xcpt_pf_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_xcpt_ae_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_xcpt_ma_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_bp_debug_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_bp_xcpt_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_1_0_bits_debug_fsrc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_1_0_bits_debug_tsrc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  input         io_dis_uops_0_0_ready,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_valid,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [6:0]  io_dis_uops_0_0_bits_uopc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [31:0] io_dis_uops_0_0_bits_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_debug_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_bits_is_rvc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [39:0] io_dis_uops_0_0_bits_debug_pc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [2:0]  io_dis_uops_0_0_bits_iq_type,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [9:0]  io_dis_uops_0_0_bits_fu_code,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_bits_is_br,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_is_jalr,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_is_jal,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_is_sfb,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [7:0]  io_dis_uops_0_0_bits_br_mask,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [2:0]  io_dis_uops_0_0_bits_br_tag,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [3:0]  io_dis_uops_0_0_bits_ftq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_bits_edge_inst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_0_0_bits_pc_lob,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_bits_taken,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [19:0] io_dis_uops_0_0_bits_imm_packed,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [11:0] io_dis_uops_0_0_bits_csr_addr,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [3:0]  io_dis_uops_0_0_bits_rob_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [2:0]  io_dis_uops_0_0_bits_ldq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_stq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_0_0_bits_rxq_idx,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_0_0_bits_pdst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_prs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_prs2,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_prs3,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_bits_prs1_busy,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_prs2_busy,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_0_0_bits_stale_pdst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_bits_exception,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [63:0] io_dis_uops_0_0_bits_exc_cause,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_bits_bypassable,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [4:0]  io_dis_uops_0_0_bits_mem_cmd,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_0_0_bits_mem_size,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_bits_mem_signed,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_is_fence,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_is_fencei,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_is_amo,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_uses_ldq,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_uses_stq,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_is_sys_pc2epc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_is_unique,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_flush_on_commit,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_ldst_is_rs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [5:0]  io_dis_uops_0_0_bits_ldst,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_lrs1,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_lrs2,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_lrs3,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_bits_ldst_val,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_0_0_bits_dst_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_lrs1_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_lrs2_rtype,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output        io_dis_uops_0_0_bits_frs3_en,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_fp_val,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_fp_single,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_xcpt_pf_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_xcpt_ae_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_xcpt_ma_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_bp_debug_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_bp_xcpt_if,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
  output [1:0]  io_dis_uops_0_0_bits_debug_fsrc,	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
                io_dis_uops_0_0_bits_debug_tsrc	// @[generators/boom/src/main/scala/exu/dispatch.scala:36:14]
);

  assign io_ren_uops_0_ready = io_dis_uops_0_0_ready & io_dis_uops_1_0_ready & io_dis_uops_2_0_ready;	// @[generators/boom/src/main/scala/exu/dispatch.scala:47:79]
  assign io_dis_uops_2_0_valid = io_ren_uops_0_valid & io_ren_uops_0_bits_iq_type[2];	// @[generators/boom/src/main/scala/exu/dispatch.scala:58:{42,75}]
  assign io_dis_uops_2_0_bits_uopc = io_ren_uops_0_bits_uopc;
  assign io_dis_uops_2_0_bits_inst = io_ren_uops_0_bits_inst;
  assign io_dis_uops_2_0_bits_debug_inst = io_ren_uops_0_bits_debug_inst;
  assign io_dis_uops_2_0_bits_is_rvc = io_ren_uops_0_bits_is_rvc;
  assign io_dis_uops_2_0_bits_debug_pc = io_ren_uops_0_bits_debug_pc;
  assign io_dis_uops_2_0_bits_iq_type = io_ren_uops_0_bits_iq_type;
  assign io_dis_uops_2_0_bits_fu_code = io_ren_uops_0_bits_fu_code;
  assign io_dis_uops_2_0_bits_is_br = io_ren_uops_0_bits_is_br;
  assign io_dis_uops_2_0_bits_is_jalr = io_ren_uops_0_bits_is_jalr;
  assign io_dis_uops_2_0_bits_is_jal = io_ren_uops_0_bits_is_jal;
  assign io_dis_uops_2_0_bits_is_sfb = io_ren_uops_0_bits_is_sfb;
  assign io_dis_uops_2_0_bits_br_mask = io_ren_uops_0_bits_br_mask;
  assign io_dis_uops_2_0_bits_br_tag = io_ren_uops_0_bits_br_tag;
  assign io_dis_uops_2_0_bits_ftq_idx = io_ren_uops_0_bits_ftq_idx;
  assign io_dis_uops_2_0_bits_edge_inst = io_ren_uops_0_bits_edge_inst;
  assign io_dis_uops_2_0_bits_pc_lob = io_ren_uops_0_bits_pc_lob;
  assign io_dis_uops_2_0_bits_taken = io_ren_uops_0_bits_taken;
  assign io_dis_uops_2_0_bits_imm_packed = io_ren_uops_0_bits_imm_packed;
  assign io_dis_uops_2_0_bits_csr_addr = io_ren_uops_0_bits_csr_addr;
  assign io_dis_uops_2_0_bits_rob_idx = io_ren_uops_0_bits_rob_idx;
  assign io_dis_uops_2_0_bits_ldq_idx = io_ren_uops_0_bits_ldq_idx;
  assign io_dis_uops_2_0_bits_stq_idx = io_ren_uops_0_bits_stq_idx;
  assign io_dis_uops_2_0_bits_rxq_idx = io_ren_uops_0_bits_rxq_idx;
  assign io_dis_uops_2_0_bits_pdst = io_ren_uops_0_bits_pdst;
  assign io_dis_uops_2_0_bits_prs1 = io_ren_uops_0_bits_prs1;
  assign io_dis_uops_2_0_bits_prs2 = io_ren_uops_0_bits_prs2;
  assign io_dis_uops_2_0_bits_prs3 = io_ren_uops_0_bits_prs3;
  assign io_dis_uops_2_0_bits_prs1_busy = io_ren_uops_0_bits_prs1_busy;
  assign io_dis_uops_2_0_bits_prs2_busy = io_ren_uops_0_bits_prs2_busy;
  assign io_dis_uops_2_0_bits_prs3_busy = io_ren_uops_0_bits_prs3_busy;
  assign io_dis_uops_2_0_bits_stale_pdst = io_ren_uops_0_bits_stale_pdst;
  assign io_dis_uops_2_0_bits_exception = io_ren_uops_0_bits_exception;
  assign io_dis_uops_2_0_bits_exc_cause = io_ren_uops_0_bits_exc_cause;
  assign io_dis_uops_2_0_bits_bypassable = io_ren_uops_0_bits_bypassable;
  assign io_dis_uops_2_0_bits_mem_cmd = io_ren_uops_0_bits_mem_cmd;
  assign io_dis_uops_2_0_bits_mem_size = io_ren_uops_0_bits_mem_size;
  assign io_dis_uops_2_0_bits_mem_signed = io_ren_uops_0_bits_mem_signed;
  assign io_dis_uops_2_0_bits_is_fence = io_ren_uops_0_bits_is_fence;
  assign io_dis_uops_2_0_bits_is_fencei = io_ren_uops_0_bits_is_fencei;
  assign io_dis_uops_2_0_bits_is_amo = io_ren_uops_0_bits_is_amo;
  assign io_dis_uops_2_0_bits_uses_ldq = io_ren_uops_0_bits_uses_ldq;
  assign io_dis_uops_2_0_bits_uses_stq = io_ren_uops_0_bits_uses_stq;
  assign io_dis_uops_2_0_bits_is_sys_pc2epc = io_ren_uops_0_bits_is_sys_pc2epc;
  assign io_dis_uops_2_0_bits_is_unique = io_ren_uops_0_bits_is_unique;
  assign io_dis_uops_2_0_bits_flush_on_commit = io_ren_uops_0_bits_flush_on_commit;
  assign io_dis_uops_2_0_bits_ldst_is_rs1 = io_ren_uops_0_bits_ldst_is_rs1;
  assign io_dis_uops_2_0_bits_ldst = io_ren_uops_0_bits_ldst;
  assign io_dis_uops_2_0_bits_lrs1 = io_ren_uops_0_bits_lrs1;
  assign io_dis_uops_2_0_bits_lrs2 = io_ren_uops_0_bits_lrs2;
  assign io_dis_uops_2_0_bits_lrs3 = io_ren_uops_0_bits_lrs3;
  assign io_dis_uops_2_0_bits_ldst_val = io_ren_uops_0_bits_ldst_val;
  assign io_dis_uops_2_0_bits_dst_rtype = io_ren_uops_0_bits_dst_rtype;
  assign io_dis_uops_2_0_bits_lrs1_rtype = io_ren_uops_0_bits_lrs1_rtype;
  assign io_dis_uops_2_0_bits_lrs2_rtype = io_ren_uops_0_bits_lrs2_rtype;
  assign io_dis_uops_2_0_bits_frs3_en = io_ren_uops_0_bits_frs3_en;
  assign io_dis_uops_2_0_bits_fp_val = io_ren_uops_0_bits_fp_val;
  assign io_dis_uops_2_0_bits_fp_single = io_ren_uops_0_bits_fp_single;
  assign io_dis_uops_2_0_bits_xcpt_pf_if = io_ren_uops_0_bits_xcpt_pf_if;
  assign io_dis_uops_2_0_bits_xcpt_ae_if = io_ren_uops_0_bits_xcpt_ae_if;
  assign io_dis_uops_2_0_bits_xcpt_ma_if = io_ren_uops_0_bits_xcpt_ma_if;
  assign io_dis_uops_2_0_bits_bp_debug_if = io_ren_uops_0_bits_bp_debug_if;
  assign io_dis_uops_2_0_bits_bp_xcpt_if = io_ren_uops_0_bits_bp_xcpt_if;
  assign io_dis_uops_2_0_bits_debug_fsrc = io_ren_uops_0_bits_debug_fsrc;
  assign io_dis_uops_2_0_bits_debug_tsrc = io_ren_uops_0_bits_debug_tsrc;
  assign io_dis_uops_1_0_valid = io_ren_uops_0_valid & io_ren_uops_0_bits_iq_type[0];	// @[generators/boom/src/main/scala/exu/dispatch.scala:58:{42,75}]
  assign io_dis_uops_1_0_bits_uopc = io_ren_uops_0_bits_uopc;
  assign io_dis_uops_1_0_bits_inst = io_ren_uops_0_bits_inst;
  assign io_dis_uops_1_0_bits_debug_inst = io_ren_uops_0_bits_debug_inst;
  assign io_dis_uops_1_0_bits_is_rvc = io_ren_uops_0_bits_is_rvc;
  assign io_dis_uops_1_0_bits_debug_pc = io_ren_uops_0_bits_debug_pc;
  assign io_dis_uops_1_0_bits_iq_type = io_ren_uops_0_bits_iq_type;
  assign io_dis_uops_1_0_bits_fu_code = io_ren_uops_0_bits_fu_code;
  assign io_dis_uops_1_0_bits_is_br = io_ren_uops_0_bits_is_br;
  assign io_dis_uops_1_0_bits_is_jalr = io_ren_uops_0_bits_is_jalr;
  assign io_dis_uops_1_0_bits_is_jal = io_ren_uops_0_bits_is_jal;
  assign io_dis_uops_1_0_bits_is_sfb = io_ren_uops_0_bits_is_sfb;
  assign io_dis_uops_1_0_bits_br_mask = io_ren_uops_0_bits_br_mask;
  assign io_dis_uops_1_0_bits_br_tag = io_ren_uops_0_bits_br_tag;
  assign io_dis_uops_1_0_bits_ftq_idx = io_ren_uops_0_bits_ftq_idx;
  assign io_dis_uops_1_0_bits_edge_inst = io_ren_uops_0_bits_edge_inst;
  assign io_dis_uops_1_0_bits_pc_lob = io_ren_uops_0_bits_pc_lob;
  assign io_dis_uops_1_0_bits_taken = io_ren_uops_0_bits_taken;
  assign io_dis_uops_1_0_bits_imm_packed = io_ren_uops_0_bits_imm_packed;
  assign io_dis_uops_1_0_bits_csr_addr = io_ren_uops_0_bits_csr_addr;
  assign io_dis_uops_1_0_bits_rob_idx = io_ren_uops_0_bits_rob_idx;
  assign io_dis_uops_1_0_bits_ldq_idx = io_ren_uops_0_bits_ldq_idx;
  assign io_dis_uops_1_0_bits_stq_idx = io_ren_uops_0_bits_stq_idx;
  assign io_dis_uops_1_0_bits_rxq_idx = io_ren_uops_0_bits_rxq_idx;
  assign io_dis_uops_1_0_bits_pdst = io_ren_uops_0_bits_pdst;
  assign io_dis_uops_1_0_bits_prs1 = io_ren_uops_0_bits_prs1;
  assign io_dis_uops_1_0_bits_prs2 = io_ren_uops_0_bits_prs2;
  assign io_dis_uops_1_0_bits_prs3 = io_ren_uops_0_bits_prs3;
  assign io_dis_uops_1_0_bits_prs1_busy = io_ren_uops_0_bits_prs1_busy;
  assign io_dis_uops_1_0_bits_prs2_busy = io_ren_uops_0_bits_prs2_busy;
  assign io_dis_uops_1_0_bits_stale_pdst = io_ren_uops_0_bits_stale_pdst;
  assign io_dis_uops_1_0_bits_exception = io_ren_uops_0_bits_exception;
  assign io_dis_uops_1_0_bits_exc_cause = io_ren_uops_0_bits_exc_cause;
  assign io_dis_uops_1_0_bits_bypassable = io_ren_uops_0_bits_bypassable;
  assign io_dis_uops_1_0_bits_mem_cmd = io_ren_uops_0_bits_mem_cmd;
  assign io_dis_uops_1_0_bits_mem_size = io_ren_uops_0_bits_mem_size;
  assign io_dis_uops_1_0_bits_mem_signed = io_ren_uops_0_bits_mem_signed;
  assign io_dis_uops_1_0_bits_is_fence = io_ren_uops_0_bits_is_fence;
  assign io_dis_uops_1_0_bits_is_fencei = io_ren_uops_0_bits_is_fencei;
  assign io_dis_uops_1_0_bits_is_amo = io_ren_uops_0_bits_is_amo;
  assign io_dis_uops_1_0_bits_uses_ldq = io_ren_uops_0_bits_uses_ldq;
  assign io_dis_uops_1_0_bits_uses_stq = io_ren_uops_0_bits_uses_stq;
  assign io_dis_uops_1_0_bits_is_sys_pc2epc = io_ren_uops_0_bits_is_sys_pc2epc;
  assign io_dis_uops_1_0_bits_is_unique = io_ren_uops_0_bits_is_unique;
  assign io_dis_uops_1_0_bits_flush_on_commit = io_ren_uops_0_bits_flush_on_commit;
  assign io_dis_uops_1_0_bits_ldst_is_rs1 = io_ren_uops_0_bits_ldst_is_rs1;
  assign io_dis_uops_1_0_bits_ldst = io_ren_uops_0_bits_ldst;
  assign io_dis_uops_1_0_bits_lrs1 = io_ren_uops_0_bits_lrs1;
  assign io_dis_uops_1_0_bits_lrs2 = io_ren_uops_0_bits_lrs2;
  assign io_dis_uops_1_0_bits_lrs3 = io_ren_uops_0_bits_lrs3;
  assign io_dis_uops_1_0_bits_ldst_val = io_ren_uops_0_bits_ldst_val;
  assign io_dis_uops_1_0_bits_dst_rtype = io_ren_uops_0_bits_dst_rtype;
  assign io_dis_uops_1_0_bits_lrs1_rtype = io_ren_uops_0_bits_lrs1_rtype;
  assign io_dis_uops_1_0_bits_lrs2_rtype = io_ren_uops_0_bits_lrs2_rtype;
  assign io_dis_uops_1_0_bits_frs3_en = io_ren_uops_0_bits_frs3_en;
  assign io_dis_uops_1_0_bits_fp_val = io_ren_uops_0_bits_fp_val;
  assign io_dis_uops_1_0_bits_fp_single = io_ren_uops_0_bits_fp_single;
  assign io_dis_uops_1_0_bits_xcpt_pf_if = io_ren_uops_0_bits_xcpt_pf_if;
  assign io_dis_uops_1_0_bits_xcpt_ae_if = io_ren_uops_0_bits_xcpt_ae_if;
  assign io_dis_uops_1_0_bits_xcpt_ma_if = io_ren_uops_0_bits_xcpt_ma_if;
  assign io_dis_uops_1_0_bits_bp_debug_if = io_ren_uops_0_bits_bp_debug_if;
  assign io_dis_uops_1_0_bits_bp_xcpt_if = io_ren_uops_0_bits_bp_xcpt_if;
  assign io_dis_uops_1_0_bits_debug_fsrc = io_ren_uops_0_bits_debug_fsrc;
  assign io_dis_uops_1_0_bits_debug_tsrc = io_ren_uops_0_bits_debug_tsrc;
  assign io_dis_uops_0_0_valid = io_ren_uops_0_valid & io_ren_uops_0_bits_iq_type[1];	// @[generators/boom/src/main/scala/exu/dispatch.scala:58:{42,75}]
  assign io_dis_uops_0_0_bits_uopc = io_ren_uops_0_bits_uopc;
  assign io_dis_uops_0_0_bits_inst = io_ren_uops_0_bits_inst;
  assign io_dis_uops_0_0_bits_debug_inst = io_ren_uops_0_bits_debug_inst;
  assign io_dis_uops_0_0_bits_is_rvc = io_ren_uops_0_bits_is_rvc;
  assign io_dis_uops_0_0_bits_debug_pc = io_ren_uops_0_bits_debug_pc;
  assign io_dis_uops_0_0_bits_iq_type = io_ren_uops_0_bits_iq_type;
  assign io_dis_uops_0_0_bits_fu_code = io_ren_uops_0_bits_fu_code;
  assign io_dis_uops_0_0_bits_is_br = io_ren_uops_0_bits_is_br;
  assign io_dis_uops_0_0_bits_is_jalr = io_ren_uops_0_bits_is_jalr;
  assign io_dis_uops_0_0_bits_is_jal = io_ren_uops_0_bits_is_jal;
  assign io_dis_uops_0_0_bits_is_sfb = io_ren_uops_0_bits_is_sfb;
  assign io_dis_uops_0_0_bits_br_mask = io_ren_uops_0_bits_br_mask;
  assign io_dis_uops_0_0_bits_br_tag = io_ren_uops_0_bits_br_tag;
  assign io_dis_uops_0_0_bits_ftq_idx = io_ren_uops_0_bits_ftq_idx;
  assign io_dis_uops_0_0_bits_edge_inst = io_ren_uops_0_bits_edge_inst;
  assign io_dis_uops_0_0_bits_pc_lob = io_ren_uops_0_bits_pc_lob;
  assign io_dis_uops_0_0_bits_taken = io_ren_uops_0_bits_taken;
  assign io_dis_uops_0_0_bits_imm_packed = io_ren_uops_0_bits_imm_packed;
  assign io_dis_uops_0_0_bits_csr_addr = io_ren_uops_0_bits_csr_addr;
  assign io_dis_uops_0_0_bits_rob_idx = io_ren_uops_0_bits_rob_idx;
  assign io_dis_uops_0_0_bits_ldq_idx = io_ren_uops_0_bits_ldq_idx;
  assign io_dis_uops_0_0_bits_stq_idx = io_ren_uops_0_bits_stq_idx;
  assign io_dis_uops_0_0_bits_rxq_idx = io_ren_uops_0_bits_rxq_idx;
  assign io_dis_uops_0_0_bits_pdst = io_ren_uops_0_bits_pdst;
  assign io_dis_uops_0_0_bits_prs1 = io_ren_uops_0_bits_prs1;
  assign io_dis_uops_0_0_bits_prs2 = io_ren_uops_0_bits_prs2;
  assign io_dis_uops_0_0_bits_prs3 = io_ren_uops_0_bits_prs3;
  assign io_dis_uops_0_0_bits_prs1_busy = io_ren_uops_0_bits_prs1_busy;
  assign io_dis_uops_0_0_bits_prs2_busy = io_ren_uops_0_bits_prs2_busy;
  assign io_dis_uops_0_0_bits_stale_pdst = io_ren_uops_0_bits_stale_pdst;
  assign io_dis_uops_0_0_bits_exception = io_ren_uops_0_bits_exception;
  assign io_dis_uops_0_0_bits_exc_cause = io_ren_uops_0_bits_exc_cause;
  assign io_dis_uops_0_0_bits_bypassable = io_ren_uops_0_bits_bypassable;
  assign io_dis_uops_0_0_bits_mem_cmd = io_ren_uops_0_bits_mem_cmd;
  assign io_dis_uops_0_0_bits_mem_size = io_ren_uops_0_bits_mem_size;
  assign io_dis_uops_0_0_bits_mem_signed = io_ren_uops_0_bits_mem_signed;
  assign io_dis_uops_0_0_bits_is_fence = io_ren_uops_0_bits_is_fence;
  assign io_dis_uops_0_0_bits_is_fencei = io_ren_uops_0_bits_is_fencei;
  assign io_dis_uops_0_0_bits_is_amo = io_ren_uops_0_bits_is_amo;
  assign io_dis_uops_0_0_bits_uses_ldq = io_ren_uops_0_bits_uses_ldq;
  assign io_dis_uops_0_0_bits_uses_stq = io_ren_uops_0_bits_uses_stq;
  assign io_dis_uops_0_0_bits_is_sys_pc2epc = io_ren_uops_0_bits_is_sys_pc2epc;
  assign io_dis_uops_0_0_bits_is_unique = io_ren_uops_0_bits_is_unique;
  assign io_dis_uops_0_0_bits_flush_on_commit = io_ren_uops_0_bits_flush_on_commit;
  assign io_dis_uops_0_0_bits_ldst_is_rs1 = io_ren_uops_0_bits_ldst_is_rs1;
  assign io_dis_uops_0_0_bits_ldst = io_ren_uops_0_bits_ldst;
  assign io_dis_uops_0_0_bits_lrs1 = io_ren_uops_0_bits_lrs1;
  assign io_dis_uops_0_0_bits_lrs2 = io_ren_uops_0_bits_lrs2;
  assign io_dis_uops_0_0_bits_lrs3 = io_ren_uops_0_bits_lrs3;
  assign io_dis_uops_0_0_bits_ldst_val = io_ren_uops_0_bits_ldst_val;
  assign io_dis_uops_0_0_bits_dst_rtype = io_ren_uops_0_bits_dst_rtype;
  assign io_dis_uops_0_0_bits_lrs1_rtype = io_ren_uops_0_bits_lrs1_rtype;
  assign io_dis_uops_0_0_bits_lrs2_rtype = io_ren_uops_0_bits_lrs2_rtype;
  assign io_dis_uops_0_0_bits_frs3_en = io_ren_uops_0_bits_frs3_en;
  assign io_dis_uops_0_0_bits_fp_val = io_ren_uops_0_bits_fp_val;
  assign io_dis_uops_0_0_bits_fp_single = io_ren_uops_0_bits_fp_single;
  assign io_dis_uops_0_0_bits_xcpt_pf_if = io_ren_uops_0_bits_xcpt_pf_if;
  assign io_dis_uops_0_0_bits_xcpt_ae_if = io_ren_uops_0_bits_xcpt_ae_if;
  assign io_dis_uops_0_0_bits_xcpt_ma_if = io_ren_uops_0_bits_xcpt_ma_if;
  assign io_dis_uops_0_0_bits_bp_debug_if = io_ren_uops_0_bits_bp_debug_if;
  assign io_dis_uops_0_0_bits_bp_xcpt_if = io_ren_uops_0_bits_bp_xcpt_if;
  assign io_dis_uops_0_0_bits_debug_fsrc = io_ren_uops_0_bits_debug_fsrc;
  assign io_dis_uops_0_0_bits_debug_tsrc = io_ren_uops_0_bits_debug_tsrc;
endmodule

