// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BoomWritebackUnit(
  input         clock,
                reset,
  output        io_req_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  input         io_req_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  input  [24:0] io_req_bits_tag,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  input         io_req_bits_idx,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  input  [2:0]  io_req_bits_param,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  input         io_req_bits_way_en,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
                io_req_bits_voluntary,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
                io_meta_read_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output        io_meta_read_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
                io_meta_read_bits_idx,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output [24:0] io_meta_read_bits_tag,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output        io_resp,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
                io_idx_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
                io_idx_bits,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  input         io_data_req_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output        io_data_req_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
                io_data_req_bits_way_en,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output [6:0]  io_data_req_bits_addr,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  input  [63:0] io_data_resp,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  input         io_mem_grant,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
                io_release_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output        io_release_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output [2:0]  io_release_bits_opcode,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
                io_release_bits_param,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output [31:0] io_release_bits_address,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output [63:0] io_release_bits_data,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  input         io_lsu_release_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output        io_lsu_release_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
  output [31:0] io_lsu_release_bits_address	// @[generators/boom/src/main/scala/lsu/dcache.scala:26:14]
);

  reg  [24:0] req_tag;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
  reg         req_idx;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
  reg  [2:0]  req_param;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
  reg         req_way_en;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
  reg         req_voluntary;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
  reg  [2:0]  state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22]
  reg         r1_data_req_fired;	// @[generators/boom/src/main/scala/lsu/dcache.scala:45:34]
  reg         r2_data_req_fired;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34]
  reg  [3:0]  r1_data_req_cnt;	// @[generators/boom/src/main/scala/lsu/dcache.scala:47:28]
  reg  [3:0]  r2_data_req_cnt;	// @[generators/boom/src/main/scala/lsu/dcache.scala:48:28]
  reg  [3:0]  data_req_cnt;	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29]
  reg  [63:0] wb_buffer_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
  reg  [63:0] wb_buffer_1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
  reg  [63:0] wb_buffer_2;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
  reg  [63:0] wb_buffer_3;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
  reg  [63:0] wb_buffer_4;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
  reg  [63:0] wb_buffer_5;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
  reg  [63:0] wb_buffer_6;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
  reg  [63:0] wb_buffer_7;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
  reg         acked;	// @[generators/boom/src/main/scala/lsu/dcache.scala:52:22]
  wire [31:0] r_address = {req_tag, req_idx, 6'h0};	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16, :68:41]
  reg  [63:0] casez_tmp;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
  always @(*) begin	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
    casez (data_req_cnt[2:0])	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
      3'b000:
        casez_tmp = wb_buffer_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
      3'b001:
        casez_tmp = wb_buffer_1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
      3'b010:
        casez_tmp = wb_buffer_2;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
      3'b011:
        casez_tmp = wb_buffer_3;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
      3'b100:
        casez_tmp = wb_buffer_4;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
      3'b101:
        casez_tmp = wb_buffer_5;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
      3'b110:
        casez_tmp = wb_buffer_6;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
      default:
        casez_tmp = wb_buffer_7;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
    endcase	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
  end // always @(*)
  wire        io_req_ready_0 = state == 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :85:15]
  wire        _GEN = state == 3'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :88:13, :93:22]
  wire        io_data_req_valid_0 = ~io_req_ready_0 & _GEN & ~(data_req_cnt[3]);	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29, :59:22, :85:{15,30}, :93:{22,41}, :94:40]
  wire        _GEN_0 = r2_data_req_cnt == 4'h7;	// @[generators/boom/src/main/scala/lsu/dcache.scala:48:28, :115:29]
  wire        _GEN_1 = state == 3'h2;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :117:15, :121:22]
  wire        io_lsu_release_valid_0 = ~(io_req_ready_0 | _GEN) & _GEN_1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:64:24, :85:{15,30}, :93:{22,41}, :121:{22,41}]
  wire        _GEN_2 = state == 3'h3;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :125:12, :127:22]
  wire        _GEN_3 = _GEN | _GEN_1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:56:22, :93:{22,41}, :121:{22,41}, :127:36]
  wire        io_release_valid_0 = ~(io_req_ready_0 | _GEN_3) & _GEN_2 & ~(data_req_cnt[3]);	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29, :56:22, :85:{15,30}, :93:41, :94:40, :121:41, :127:{22,36}, :128:38]
  wire        _GEN_4 = io_release_ready & io_release_valid_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:56:22, :85:30, :93:41, :121:41, :127:36, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_5 = state == 3'h4;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :138:19, :140:22]
  wire        _GEN_6 = io_req_ready_0 & io_req_valid;	// @[generators/boom/src/main/scala/lsu/dcache.scala:85:15, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_7 = io_req_ready_0 | ~_GEN;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :85:{15,30}, :93:{22,41}]
  wire        _GEN_8 = io_data_req_ready & io_data_req_valid_0 & io_meta_read_ready;	// @[generators/boom/src/main/scala/lsu/dcache.scala:59:22, :85:30, :93:41, :108:28]
  always @(posedge clock) begin
    if (io_req_ready_0 & _GEN_6) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16, :85:{15,30}, :87:24, :90:11, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      req_tag <= io_req_bits_tag;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
      req_idx <= io_req_bits_idx;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
      req_param <= io_req_bits_param;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
      req_way_en <= io_req_bits_way_en;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
      req_voluntary <= io_req_bits_voluntary;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
    end
    if (_GEN_7) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :48:28, :85:30, :93:41]
    end
    else begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:48:28, :85:30, :93:41]
      r1_data_req_cnt <= _GEN_8 ? data_req_cnt : 4'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:47:28, :49:29, :105:23, :108:{28,50}, :110:25]
      r2_data_req_cnt <= r1_data_req_cnt;	// @[generators/boom/src/main/scala/lsu/dcache.scala:47:28, :48:28]
    end
    if (io_req_ready_0 | ~(_GEN & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h0)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :46:34, :48:28, :51:22, :85:{15,30}, :93:{22,41}, :113:30, :114:34]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :85:30, :93:41]
      wb_buffer_0 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
    if (io_req_ready_0 | ~(_GEN & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h1)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :48:28, :51:22, :85:{15,30}, :88:13, :93:{22,41}, :113:30, :114:34]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :85:30, :93:41]
      wb_buffer_1 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
    if (io_req_ready_0 | ~(_GEN & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h2)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :48:28, :51:22, :85:{15,30}, :93:{22,41}, :113:30, :114:34, :117:15]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :85:30, :93:41]
      wb_buffer_2 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
    if (io_req_ready_0 | ~(_GEN & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h3)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :48:28, :51:22, :85:{15,30}, :93:{22,41}, :113:30, :114:34, :125:12]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :85:30, :93:41]
      wb_buffer_3 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
    if (io_req_ready_0 | ~(_GEN & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h4)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :48:28, :51:22, :85:{15,30}, :93:{22,41}, :113:30, :114:34, :138:19]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :85:30, :93:41]
      wb_buffer_4 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
    if (io_req_ready_0 | ~(_GEN & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h5)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :48:28, :51:22, :85:{15,30}, :93:{22,41}, :113:30, :114:34, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:435:15]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :85:30, :93:41]
      wb_buffer_5 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
    if (io_req_ready_0 | ~(_GEN & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h6)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :48:28, :51:22, :85:{15,30}, :93:{22,41}, :113:30, :114:34, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:437:15]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :85:30, :93:41]
      wb_buffer_6 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
    if (io_req_ready_0 | ~(_GEN & r2_data_req_fired & (&(r2_data_req_cnt[2:0])))) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :48:28, :51:22, :85:{15,30}, :93:{22,41}, :113:30, :114:34]
    end
    else	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22, :85:30, :93:41]
      wb_buffer_7 <= io_data_resp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:51:22]
    if (reset) begin
      state <= 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22]
      r1_data_req_fired <= 1'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16, :45:34]
      r2_data_req_fired <= 1'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16, :46:34]
      data_req_cnt <= 4'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29]
      acked <= 1'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16, :52:22]
    end
    else begin
      if (io_req_ready_0) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:85:15]
        if (_GEN_6) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
          state <= 3'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :88:13]
          data_req_cnt <= 4'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29]
        end
        acked <= ~_GEN_6 & acked;	// @[generators/boom/src/main/scala/lsu/dcache.scala:52:22, :87:24, :91:13, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      end
      else begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:85:15]
        if (_GEN) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:93:22]
          if (r2_data_req_fired & _GEN_0) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :46:34, :113:30, :115:{29,53}, :117:15]
            state <= 3'h2;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :117:15]
            data_req_cnt <= 4'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29]
          end
          else if (_GEN_8)	// @[generators/boom/src/main/scala/lsu/dcache.scala:108:28]
            data_req_cnt <= data_req_cnt + 4'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29, :111:36]
        end
        else begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:93:22]
          if (_GEN_1) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:121:22]
            if (io_lsu_release_ready & io_lsu_release_valid_0)	// @[generators/boom/src/main/scala/lsu/dcache.scala:64:24, :85:30, :93:41, :121:41, src/main/scala/chisel3/util/Decoupled.scala:52:35]
              state <= 3'h3;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :125:12]
          end
          else if (_GEN_2) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:127:22]
            if (data_req_cnt == 4'h7 & _GEN_4)	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29, :115:29, :137:{25,49}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
              state <= {req_voluntary, 2'h0};	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16, :44:22, :138:19]
          end
          else if (_GEN_5 & acked)	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :52:22, :140:{22,35}, :144:18, :145:13]
            state <= 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22]
          if (_GEN_1 | ~(_GEN_2 & _GEN_4)) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29, :121:{22,41}, :127:{22,36}, :134:28, :135:20, src/main/scala/chisel3/util/Decoupled.scala:52:35]
          end
          else	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29, :121:41, :127:36]
            data_req_cnt <= data_req_cnt + 4'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:49:29, :111:36, :135:36]
        end
        if (~_GEN_3) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:56:22, :93:41, :121:41, :127:36]
          if (_GEN_2)	// @[generators/boom/src/main/scala/lsu/dcache.scala:127:22]
            acked <= io_mem_grant | acked;	// @[generators/boom/src/main/scala/lsu/dcache.scala:52:22, :131:25, :132:13]
          else	// @[generators/boom/src/main/scala/lsu/dcache.scala:127:22]
            acked <= _GEN_5 & io_mem_grant | acked;	// @[generators/boom/src/main/scala/lsu/dcache.scala:52:22, :140:{22,35}, :141:25, :142:13]
        end
      end
      if (_GEN_7) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :85:30, :93:41]
      end
      else begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :85:30, :93:41]
        r1_data_req_fired <= _GEN_8;	// @[generators/boom/src/main/scala/lsu/dcache.scala:45:34, :108:28]
        r2_data_req_fired <= r1_data_req_fired;	// @[generators/boom/src/main/scala/lsu/dcache.scala:45:34, :46:34]
      end
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:85:15]
  assign io_meta_read_valid = io_data_req_valid_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:59:22, :85:30, :93:41]
  assign io_meta_read_bits_idx = req_idx;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
  assign io_meta_read_bits_tag = req_tag;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
  assign io_resp = ~io_req_ready_0 & _GEN & r2_data_req_fired & _GEN_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:46:34, :59:22, :63:22, :85:{15,30}, :93:{22,41}, :115:29]
  assign io_idx_valid = |state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:44:22, :54:31]
  assign io_idx_bits = req_idx;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
  assign io_data_req_valid = io_data_req_valid_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:59:22, :85:30, :93:41]
  assign io_data_req_bits_way_en = req_way_en;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
  assign io_data_req_bits_addr = {req_idx, data_req_cnt[2:0], 3'h0};	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16, :44:22, :49:29, :102:43]
  assign io_release_valid = io_release_valid_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:56:22, :85:30, :93:41, :121:41, :127:36]
  assign io_release_bits_opcode = {1'h1, req_voluntary, 1'h1};	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16, :129:27, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:28]
  assign io_release_bits_param = req_param;	// @[generators/boom/src/main/scala/lsu/dcache.scala:42:16]
  assign io_release_bits_address = r_address;	// @[generators/boom/src/main/scala/lsu/dcache.scala:68:41]
  assign io_release_bits_data = casez_tmp;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:442:15]
  assign io_lsu_release_valid = io_lsu_release_valid_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:64:24, :85:30, :93:41, :121:41]
  assign io_lsu_release_bits_address = r_address;	// @[generators/boom/src/main/scala/lsu/dcache.scala:68:41]
endmodule

