// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BoomRAS(
  input         clock,
  input  [4:0]  io_read_idx,	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:28:14]
  output [39:0] io_read_addr,	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:28:14]
  input         io_write_valid,	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:28:14]
  input  [4:0]  io_write_idx,	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:28:14]
  input  [39:0] io_write_addr	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:28:14]
);

  reg [39:0] ras_0;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_1;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_2;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_3;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_4;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_5;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_6;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_7;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_8;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_9;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_10;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_11;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_12;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_13;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_14;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_15;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_16;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_17;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_18;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_19;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_20;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_21;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_22;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_23;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_24;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_25;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_26;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_27;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_28;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_29;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_30;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg [39:0] ras_31;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
  reg        io_read_addr_REG;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:38:30]
  reg [39:0] io_read_addr_REG_1;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:39:12]
  reg [39:0] io_read_addr_REG_2;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:40:12]
  reg [39:0] casez_tmp;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:40:12]
  always @(*) begin	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:40:12]
    casez (io_read_idx)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:40:12]
      5'b00000:
        casez_tmp = ras_0;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b00001:
        casez_tmp = ras_1;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b00010:
        casez_tmp = ras_2;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b00011:
        casez_tmp = ras_3;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b00100:
        casez_tmp = ras_4;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b00101:
        casez_tmp = ras_5;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b00110:
        casez_tmp = ras_6;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b00111:
        casez_tmp = ras_7;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b01000:
        casez_tmp = ras_8;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b01001:
        casez_tmp = ras_9;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b01010:
        casez_tmp = ras_10;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b01011:
        casez_tmp = ras_11;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b01100:
        casez_tmp = ras_12;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b01101:
        casez_tmp = ras_13;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b01110:
        casez_tmp = ras_14;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b01111:
        casez_tmp = ras_15;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b10000:
        casez_tmp = ras_16;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b10001:
        casez_tmp = ras_17;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b10010:
        casez_tmp = ras_18;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b10011:
        casez_tmp = ras_19;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b10100:
        casez_tmp = ras_20;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b10101:
        casez_tmp = ras_21;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b10110:
        casez_tmp = ras_22;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b10111:
        casez_tmp = ras_23;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b11000:
        casez_tmp = ras_24;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b11001:
        casez_tmp = ras_25;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b11010:
        casez_tmp = ras_26;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b11011:
        casez_tmp = ras_27;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b11100:
        casez_tmp = ras_28;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b11101:
        casez_tmp = ras_29;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      5'b11110:
        casez_tmp = ras_30;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
      default:
        casez_tmp = ras_31;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :40:12]
    endcase	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:40:12]
  end // always @(*)
  always @(posedge clock) begin
    if (io_write_valid & io_write_idx == 5'h0)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_0 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h1)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_1 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h2)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_2 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h3)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_3 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h4)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_4 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h5)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_5 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h6)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_6 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h7)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_7 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h8)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_8 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h9)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_9 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'hA)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_10 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'hB)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_11 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'hC)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_12 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'hD)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_13 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'hE)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_14 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'hF)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_15 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h10)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_16 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h11)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_17 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h12)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_18 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h13)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_19 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h14)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_20 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h15)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_21 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h16)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_22 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h17)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_23 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h18)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_24 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h19)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_25 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h1A)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_26 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h1B)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_27 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h1C)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_28 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h1D)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_29 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & io_write_idx == 5'h1E)	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_30 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    if (io_write_valid & (&io_write_idx))	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16, :42:25, :43:23]
      ras_31 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:36:16]
    io_read_addr_REG <= io_write_valid & io_write_idx == io_read_idx;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:38:{30,46,62}]
    io_read_addr_REG_1 <= io_write_addr;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:39:12]
    io_read_addr_REG_2 <= casez_tmp;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:40:12]
  end // always @(posedge)
  assign io_read_addr = io_read_addr_REG ? io_read_addr_REG_1 : io_read_addr_REG_2;	// @[generators/boom/src/main/scala/ifu/bpd/ras.scala:38:{22,30}, :39:12, :40:12]
endmodule

