// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BoomProbeUnit(
  input         clock,
                reset,
  output        io_req_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input         io_req_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input  [1:0]  io_req_bits_param,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input  [3:0]  io_req_bits_size,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input  [1:0]  io_req_bits_source,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input  [31:0] io_req_bits_address,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input         io_rep_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output        io_rep_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [2:0]  io_rep_bits_param,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [3:0]  io_rep_bits_size,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [1:0]  io_rep_bits_source,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [31:0] io_rep_bits_address,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input         io_meta_read_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output        io_meta_read_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
                io_meta_read_bits_idx,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [24:0] io_meta_read_bits_tag,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input         io_meta_write_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output        io_meta_write_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
                io_meta_write_bits_idx,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [1:0]  io_meta_write_bits_data_coh_state,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [24:0] io_meta_write_bits_data_tag,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input         io_wb_req_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output        io_wb_req_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [24:0] io_wb_req_bits_tag,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output        io_wb_req_bits_idx,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [2:0]  io_wb_req_bits_param,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output        io_wb_req_bits_way_en,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input         io_way_en,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
                io_wb_rdy,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
                io_mshr_rdy,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output        io_mshr_wb_rdy,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input  [1:0]  io_block_state_state,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  input         io_lsu_release_ready,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output        io_lsu_release_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [31:0] io_lsu_release_bits_address,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output        io_state_valid,	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
  output [39:0] io_state_bits	// @[generators/boom/src/main/scala/lsu/dcache.scala:162:14]
);

  reg  [3:0]  state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22]
  reg  [1:0]  req_param;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
  reg  [3:0]  req_size;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
  reg  [1:0]  req_source;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
  reg  [31:0] req_address;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
  reg         way_en;	// @[generators/boom/src/main/scala/lsu/dcache.scala:187:19]
  reg  [1:0]  old_coh_state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:189:20]
  wire [3:0]  _GEN = {req_param, way_en ? old_coh_state : 2'h0};	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16, :187:19, :189:20, :191:22, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, :161:16]
  wire        _GEN_0 = _GEN == 4'hB;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, :130:10, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_1 = _GEN == 4'h4;	// @[generators/boom/src/main/scala/lsu/dcache.scala:247:17, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_2 = _GEN == 4'h5;	// @[generators/boom/src/main/scala/lsu/dcache.scala:227:33, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_3 = _GEN == 4'h6;	// @[generators/boom/src/main/scala/lsu/dcache.scala:198:25, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_4 = _GEN == 4'h7;	// @[generators/boom/src/main/scala/lsu/dcache.scala:216:28, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_5 = _GEN == 4'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_6 = _GEN == 4'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:204:31, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_7 = _GEN == 4'h2;	// @[generators/boom/src/main/scala/lsu/dcache.scala:238:13, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_8 = _GEN == 4'h3;	// @[generators/boom/src/main/scala/lsu/dcache.scala:242:11, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire        _GEN_9 = _GEN_8 | _GEN_7;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:38:36, :56:20]
  wire [2:0]  report_param = _GEN_9 ? 3'h3 : _GEN_6 ? 3'h4 : _GEN_5 ? 3'h5 : _GEN_4 | _GEN_3 ? 3'h0 : _GEN_2 ? 3'h4 : _GEN_1 ? 3'h5 : _GEN_0 | _GEN == 4'hA ? 3'h1 : _GEN == 4'h9 ? 3'h2 : _GEN == 4'h8 ? 3'h5 : 3'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:209:32, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:38:36, :56:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  wire        io_req_ready_0 = state == 4'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25]
  wire        io_rep_valid_0 = state == 4'h6;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :198:25]
  wire        io_meta_read_valid_0 = state == 4'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :204:31]
  wire        io_meta_write_valid_0 = state == 4'h9;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :209:32]
  wire        io_wb_req_valid_0 = state == 4'h7;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :216:28]
  wire        io_lsu_release_valid_0 = state == 4'h5;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :227:33]
  wire        _GEN_10 = io_req_ready_0 & io_req_valid;	// @[generators/boom/src/main/scala/lsu/dcache.scala:197:25, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg  [3:0]  casez_tmp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:231:30, :232:24, :236:39]
  always @(*) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
    casez (state)	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      4'b0000:
        casez_tmp = _GEN_10 ? 4'h1 : state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :233:13, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      4'b0001:
        casez_tmp = io_meta_read_ready & io_meta_read_valid_0 ? 4'h2 : state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :238:13, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      4'b0010:
        casez_tmp = 4'h3;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      4'b0011:
        casez_tmp = io_mshr_rdy & io_wb_rdy ? 4'h4 : 4'h1;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:{11,17,30}, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      4'b0100:
        casez_tmp = {2'h1, way_en & (_GEN_8 | ~(_GEN_7 | _GEN_6 | _GEN_5) & (_GEN_4 | ~(_GEN_3 | _GEN_2 | _GEN_1) & _GEN_0)), 1'h1};	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :187:19, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:{11,17,30}, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:124:10, generators/rocket-chip/src/main/scala/util/Misc.scala:38:9, :56:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      4'b0101:
        casez_tmp = io_lsu_release_ready & io_lsu_release_valid_0 ? 4'h6 : state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :252:13, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      4'b0110:
        casez_tmp = io_rep_ready ? (way_en ? 4'h9 : 4'h0) : state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :187:19, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :256:{13,19}, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      4'b0111:
        casez_tmp = io_wb_req_ready & io_wb_req_valid_0 ? 4'h8 : state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :260:13, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      4'b1000:
        casez_tmp = io_wb_req_ready ? 4'h9 : state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :265:13, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      4'b1001:
        casez_tmp = io_meta_write_ready & io_meta_write_valid_0 ? 4'hA : state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :269:13, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      4'b1010:
        casez_tmp = 4'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      4'b1011:
        casez_tmp = state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      4'b1100:
        casez_tmp = state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      4'b1101:
        casez_tmp = state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      4'b1110:
        casez_tmp = state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
      default:
        casez_tmp = state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
    endcase	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :197:25, :198:25, :204:31, :209:32, :216:28, :227:33, :231:30, :232:24, :236:39, :237:30, :240:{22,39}, :242:11, :243:{22,38}, :247:11, :248:{22,39}, :249:11, :250:41, :251:32, :254:37, :255:25, :258:43, :259:27, :262:44, :264:28, :267:40, :268:31, :271:45, :272:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
  end // always @(*)
  always @(posedge clock) begin
    if (reset)
      state <= 4'h0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22]
    else
      state <= casez_tmp;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :231:30, :232:24, :236:39]
    if (io_req_ready_0 & _GEN_10) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16, :197:25, :231:30, :232:24, :234:11, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      req_param <= io_req_bits_param;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
      req_size <= io_req_bits_size;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
      req_source <= io_req_bits_source;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
      req_address <= io_req_bits_address;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
    end
    if (io_req_ready_0 | io_meta_read_valid_0 | state == 4'h2 | state != 4'h3) begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :189:20, :197:25, :204:31, :231:30, :236:39, :238:13, :240:{22,39}, :242:11, :243:{22,38}]
    end
    else begin	// @[generators/boom/src/main/scala/lsu/dcache.scala:189:20, :231:30, :236:39, :240:39, :243:38]
      way_en <= io_way_en;	// @[generators/boom/src/main/scala/lsu/dcache.scala:187:19]
      old_coh_state <= io_block_state_state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:189:20]
    end
  end // always @(posedge)
  assign io_req_ready = io_req_ready_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:197:25]
  assign io_rep_valid = io_rep_valid_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:198:25]
  assign io_rep_bits_param = report_param;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:38:36]
  assign io_rep_bits_size = req_size;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
  assign io_rep_bits_source = req_source;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
  assign io_rep_bits_address = req_address;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
  assign io_meta_read_valid = io_meta_read_valid_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:204:31]
  assign io_meta_read_bits_idx = req_address[6];	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16, :184:28]
  assign io_meta_read_bits_tag = req_address[31:7];	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16, :185:29]
  assign io_meta_write_valid = io_meta_write_valid_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:209:32]
  assign io_meta_write_bits_idx = req_address[6];	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16, :184:28]
  assign io_meta_write_bits_data_coh_state = _GEN_9 ? 2'h2 : _GEN_6 ? 2'h1 : _GEN_5 ? 2'h0 : {1'h0, _GEN_4 | _GEN_3 | _GEN_2};	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:123:10, :124:10, :161:16, generators/rocket-chip/src/main/scala/util/Misc.scala:38:{36,63}, :56:20]
  assign io_meta_write_bits_data_tag = req_address[31:7];	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16, :185:29]
  assign io_wb_req_valid = io_wb_req_valid_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:216:28]
  assign io_wb_req_bits_tag = req_address[31:7];	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16, :185:29]
  assign io_wb_req_bits_idx = req_address[6];	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16, :184:28]
  assign io_wb_req_bits_param = report_param;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:38:36]
  assign io_wb_req_bits_way_en = way_en;	// @[generators/boom/src/main/scala/lsu/dcache.scala:187:19]
  assign io_mshr_wb_rdy = ~(io_rep_valid_0 | io_wb_req_valid_0 | state == 4'h8 | io_meta_write_valid_0 | state == 4'hA);	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :198:25, :209:32, :216:28, :225:21, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :73:59]
  assign io_lsu_release_valid = io_lsu_release_valid_0;	// @[generators/boom/src/main/scala/lsu/dcache.scala:227:33]
  assign io_lsu_release_bits_address = req_address;	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16]
  assign io_state_valid = |state;	// @[generators/boom/src/main/scala/lsu/dcache.scala:181:22, :194:27]
  assign io_state_bits = {8'h0, req_address};	// @[generators/boom/src/main/scala/lsu/dcache.scala:183:16, :195:18]
endmodule

