// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BranchPredictor(
  input          clock,
                 reset,
                 io_f0_req_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input  [39:0]  io_f0_req_bits_pc,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input  [63:0]  io_f0_req_bits_ghist_old_history,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f1_preds_0_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_0_is_br,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_0_is_jal,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_0_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f1_preds_0_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f1_preds_1_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_1_is_br,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_1_is_jal,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_1_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f1_preds_1_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f1_preds_2_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_2_is_br,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_2_is_jal,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_2_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f1_preds_2_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f1_preds_3_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_3_is_br,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_3_is_jal,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f1_preds_3_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f1_preds_3_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f2_preds_0_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_0_is_br,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_0_is_jal,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_0_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f2_preds_0_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f2_preds_1_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_1_is_br,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_1_is_jal,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_1_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f2_preds_1_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f2_preds_2_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_2_is_br,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_2_is_jal,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_2_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f2_preds_2_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f2_preds_3_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_3_is_br,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_3_is_jal,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f2_preds_3_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f2_preds_3_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f3_pc,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f3_preds_0_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f3_preds_0_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f3_preds_0_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f3_preds_1_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f3_preds_1_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f3_preds_1_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f3_preds_2_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f3_preds_2_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f3_preds_2_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output         io_resp_f3_preds_3_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_resp_f3_preds_3_predicted_pc_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [39:0]  io_resp_f3_preds_3_predicted_pc_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  output [119:0] io_resp_f3_meta_0,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input          io_f3_fire,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_update_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_update_bits_is_mispredict_update,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_update_bits_is_repair_update,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input  [3:0]   io_update_bits_btb_mispredicts,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input  [39:0]  io_update_bits_pc,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input  [3:0]   io_update_bits_br_mask,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input          io_update_bits_cfi_idx_valid,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input  [1:0]   io_update_bits_cfi_idx_bits,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input          io_update_bits_cfi_taken,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_update_bits_cfi_mispredicted,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_update_bits_cfi_is_br,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
                 io_update_bits_cfi_is_jal,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input  [63:0]  io_update_bits_ghist_old_history,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input  [39:0]  io_update_bits_target,	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
  input  [119:0] io_update_bits_meta_0	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14]
);

  wire [6:0]  _banked_predictors_0_io_f0_mask_T = 7'hF << io_f0_req_bits_pc[2:1];	// @[generators/boom/src/main/scala/ifu/frontend.scala:179:31, generators/rocket-chip/src/main/scala/util/package.scala:155:13]
  reg  [63:0] banked_predictors_0_io_f1_ghist_REG;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:240:48]
  reg  [39:0] io_resp_f1_pc_REG;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:363:27]
  reg  [39:0] io_resp_f2_pc_REG;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:364:27]
  reg  [39:0] io_resp_f3_pc_REG;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:365:27]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:469:13]
    wire [3:0] _GEN = io_update_bits_br_mask >> io_update_bits_cfi_idx_bits;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:469:36]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:469:13]
      if (io_update_valid & io_update_bits_cfi_is_br & io_update_bits_cfi_idx_valid & ~reset & ~(_GEN[0])) begin	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:469:{13,36}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:469:13]
          $error("Assertion failed\n    at predictor.scala:469 assert(io.update.bits.br_mask(io.update.bits.cfi_idx.bits))\n");	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:469:13]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:469:13]
          $fatal;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:469:13]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    banked_predictors_0_io_f1_ghist_REG <= io_f0_req_bits_ghist_old_history;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:240:48]
    io_resp_f1_pc_REG <= io_f0_req_bits_pc;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:363:27]
    io_resp_f2_pc_REG <= io_resp_f1_pc_REG;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:363:27, :364:27]
    io_resp_f3_pc_REG <= io_resp_f2_pc_REG;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:364:27, :365:27]
  end // always @(posedge)
  ComposedBranchPredictorBank banked_predictors_0 (	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:219:19]
    .clock                               (clock),
    .reset                               (reset),
    .io_f0_valid                         (io_f0_req_valid),
    .io_f0_pc                            ({io_f0_req_bits_pc[39:3], 3'h0}),	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14, generators/boom/src/main/scala/ifu/frontend.scala:162:{31,39}]
    .io_f0_mask                          (_banked_predictors_0_io_f0_mask_T[3:0]),	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:238:38, generators/boom/src/main/scala/ifu/frontend.scala:179:31]
    .io_f1_ghist                         (banked_predictors_0_io_f1_ghist_REG),	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:240:48]
    .io_resp_f1_0_taken                  (io_resp_f1_preds_0_taken),
    .io_resp_f1_0_is_br                  (io_resp_f1_preds_0_is_br),
    .io_resp_f1_0_is_jal                 (io_resp_f1_preds_0_is_jal),
    .io_resp_f1_0_predicted_pc_valid     (io_resp_f1_preds_0_predicted_pc_valid),
    .io_resp_f1_0_predicted_pc_bits      (io_resp_f1_preds_0_predicted_pc_bits),
    .io_resp_f1_1_taken                  (io_resp_f1_preds_1_taken),
    .io_resp_f1_1_is_br                  (io_resp_f1_preds_1_is_br),
    .io_resp_f1_1_is_jal                 (io_resp_f1_preds_1_is_jal),
    .io_resp_f1_1_predicted_pc_valid     (io_resp_f1_preds_1_predicted_pc_valid),
    .io_resp_f1_1_predicted_pc_bits      (io_resp_f1_preds_1_predicted_pc_bits),
    .io_resp_f1_2_taken                  (io_resp_f1_preds_2_taken),
    .io_resp_f1_2_is_br                  (io_resp_f1_preds_2_is_br),
    .io_resp_f1_2_is_jal                 (io_resp_f1_preds_2_is_jal),
    .io_resp_f1_2_predicted_pc_valid     (io_resp_f1_preds_2_predicted_pc_valid),
    .io_resp_f1_2_predicted_pc_bits      (io_resp_f1_preds_2_predicted_pc_bits),
    .io_resp_f1_3_taken                  (io_resp_f1_preds_3_taken),
    .io_resp_f1_3_is_br                  (io_resp_f1_preds_3_is_br),
    .io_resp_f1_3_is_jal                 (io_resp_f1_preds_3_is_jal),
    .io_resp_f1_3_predicted_pc_valid     (io_resp_f1_preds_3_predicted_pc_valid),
    .io_resp_f1_3_predicted_pc_bits      (io_resp_f1_preds_3_predicted_pc_bits),
    .io_resp_f2_0_taken                  (io_resp_f2_preds_0_taken),
    .io_resp_f2_0_is_br                  (io_resp_f2_preds_0_is_br),
    .io_resp_f2_0_is_jal                 (io_resp_f2_preds_0_is_jal),
    .io_resp_f2_0_predicted_pc_valid     (io_resp_f2_preds_0_predicted_pc_valid),
    .io_resp_f2_0_predicted_pc_bits      (io_resp_f2_preds_0_predicted_pc_bits),
    .io_resp_f2_1_taken                  (io_resp_f2_preds_1_taken),
    .io_resp_f2_1_is_br                  (io_resp_f2_preds_1_is_br),
    .io_resp_f2_1_is_jal                 (io_resp_f2_preds_1_is_jal),
    .io_resp_f2_1_predicted_pc_valid     (io_resp_f2_preds_1_predicted_pc_valid),
    .io_resp_f2_1_predicted_pc_bits      (io_resp_f2_preds_1_predicted_pc_bits),
    .io_resp_f2_2_taken                  (io_resp_f2_preds_2_taken),
    .io_resp_f2_2_is_br                  (io_resp_f2_preds_2_is_br),
    .io_resp_f2_2_is_jal                 (io_resp_f2_preds_2_is_jal),
    .io_resp_f2_2_predicted_pc_valid     (io_resp_f2_preds_2_predicted_pc_valid),
    .io_resp_f2_2_predicted_pc_bits      (io_resp_f2_preds_2_predicted_pc_bits),
    .io_resp_f2_3_taken                  (io_resp_f2_preds_3_taken),
    .io_resp_f2_3_is_br                  (io_resp_f2_preds_3_is_br),
    .io_resp_f2_3_is_jal                 (io_resp_f2_preds_3_is_jal),
    .io_resp_f2_3_predicted_pc_valid     (io_resp_f2_preds_3_predicted_pc_valid),
    .io_resp_f2_3_predicted_pc_bits      (io_resp_f2_preds_3_predicted_pc_bits),
    .io_resp_f3_0_taken                  (io_resp_f3_preds_0_taken),
    .io_resp_f3_0_predicted_pc_valid     (io_resp_f3_preds_0_predicted_pc_valid),
    .io_resp_f3_0_predicted_pc_bits      (io_resp_f3_preds_0_predicted_pc_bits),
    .io_resp_f3_1_taken                  (io_resp_f3_preds_1_taken),
    .io_resp_f3_1_predicted_pc_valid     (io_resp_f3_preds_1_predicted_pc_valid),
    .io_resp_f3_1_predicted_pc_bits      (io_resp_f3_preds_1_predicted_pc_bits),
    .io_resp_f3_2_taken                  (io_resp_f3_preds_2_taken),
    .io_resp_f3_2_predicted_pc_valid     (io_resp_f3_preds_2_predicted_pc_valid),
    .io_resp_f3_2_predicted_pc_bits      (io_resp_f3_preds_2_predicted_pc_bits),
    .io_resp_f3_3_taken                  (io_resp_f3_preds_3_taken),
    .io_resp_f3_3_predicted_pc_valid     (io_resp_f3_preds_3_predicted_pc_valid),
    .io_resp_f3_3_predicted_pc_bits      (io_resp_f3_preds_3_predicted_pc_bits),
    .io_f3_meta                          (io_resp_f3_meta_0),
    .io_f3_fire                          (io_f3_fire),
    .io_update_valid                     (io_update_valid),
    .io_update_bits_is_mispredict_update (io_update_bits_is_mispredict_update),
    .io_update_bits_is_repair_update     (io_update_bits_is_repair_update),
    .io_update_bits_btb_mispredicts      (io_update_bits_btb_mispredicts),
    .io_update_bits_pc                   ({io_update_bits_pc[39:3], 3'h0}),	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:198:14, generators/boom/src/main/scala/ifu/frontend.scala:162:{31,39}]
    .io_update_bits_br_mask              (io_update_bits_br_mask),
    .io_update_bits_cfi_idx_valid        (io_update_bits_cfi_idx_valid),
    .io_update_bits_cfi_idx_bits         (io_update_bits_cfi_idx_bits),
    .io_update_bits_cfi_taken            (io_update_bits_cfi_taken),
    .io_update_bits_cfi_mispredicted     (io_update_bits_cfi_mispredicted),
    .io_update_bits_cfi_is_br            (io_update_bits_cfi_is_br),
    .io_update_bits_cfi_is_jal           (io_update_bits_cfi_is_jal),
    .io_update_bits_ghist                (io_update_bits_ghist_old_history),
    .io_update_bits_target               (io_update_bits_target),
    .io_update_bits_meta                 (io_update_bits_meta_0)
  );
  assign io_resp_f3_pc = io_resp_f3_pc_REG;	// @[generators/boom/src/main/scala/ifu/bpd/predictor.scala:365:27]
endmodule

