// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BranchKillableQueue_2(
  input         clock,
                reset,
  output        io_enq_ready,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  input         io_enq_valid,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  input  [7:0]  io_enq_bits_uop_br_mask,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  input  [3:0]  io_enq_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  input  [2:0]  io_enq_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
                io_enq_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  input         io_enq_bits_uop_is_amo,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
                io_enq_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
                io_enq_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  input  [63:0] io_enq_bits_data,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  input         io_enq_bits_is_hella,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
                io_deq_ready,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  output        io_deq_valid,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  output [7:0]  io_deq_bits_uop_br_mask,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  output [3:0]  io_deq_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  output [2:0]  io_deq_bits_uop_ldq_idx,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
                io_deq_bits_uop_stq_idx,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  output        io_deq_bits_uop_is_amo,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
                io_deq_bits_uop_uses_ldq,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
                io_deq_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  output [63:0] io_deq_bits_data,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  output        io_deq_bits_is_hella,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  input  [7:0]  io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
                io_brupdate_b1_mispredict_mask,	// @[generators/boom/src/main/scala/util/util.scala:454:14]
  input         io_flush	// @[generators/boom/src/main/scala/util/util.scala:454:14]
);

  reg  [1:0]  deq_ptr_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg  [63:0] ram_0_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  reg         ram_0_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  reg  [63:0] ram_1_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  reg         ram_1_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  reg  [63:0] ram_2_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  reg         ram_2_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  reg  [63:0] ram_3_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  reg         ram_3_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  reg  [63:0] casez_tmp;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  always @(*) begin	// @[generators/boom/src/main/scala/util/util.scala:465:20]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40]
      2'b00:
        casez_tmp = ram_0_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      2'b01:
        casez_tmp = ram_1_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      2'b10:
        casez_tmp = ram_2_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      default:
        casez_tmp = ram_3_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
    endcase	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg         casez_tmp_0;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  always @(*) begin	// @[generators/boom/src/main/scala/util/util.scala:465:20]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40]
      2'b00:
        casez_tmp_0 = ram_0_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      2'b01:
        casez_tmp_0 = ram_1_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      2'b10:
        casez_tmp_0 = ram_2_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      default:
        casez_tmp_0 = ram_3_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
    endcase	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg         valids_0;	// @[generators/boom/src/main/scala/util/util.scala:466:24]
  reg         valids_1;	// @[generators/boom/src/main/scala/util/util.scala:466:24]
  reg         valids_2;	// @[generators/boom/src/main/scala/util/util.scala:466:24]
  reg         valids_3;	// @[generators/boom/src/main/scala/util/util.scala:466:24]
  reg  [7:0]  uops_0_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [3:0]  uops_0_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [2:0]  uops_0_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [2:0]  uops_0_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_0_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_0_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_0_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [7:0]  uops_1_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [3:0]  uops_1_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [2:0]  uops_1_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [2:0]  uops_1_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_1_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_1_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_1_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [7:0]  uops_2_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [3:0]  uops_2_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [2:0]  uops_2_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [2:0]  uops_2_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_2_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_2_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_2_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [7:0]  uops_3_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [3:0]  uops_3_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [2:0]  uops_3_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [2:0]  uops_3_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_3_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_3_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg         uops_3_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
  reg  [1:0]  enq_ptr_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         maybe_full;	// @[generators/boom/src/main/scala/util/util.scala:471:27]
  wire        ptr_match = enq_ptr_value == deq_ptr_value;	// @[generators/boom/src/main/scala/util/util.scala:473:33, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        io_empty = ptr_match & ~maybe_full;	// @[generators/boom/src/main/scala/util/util.scala:471:27, :473:33, :474:{25,28}]
  wire        full = ptr_match & maybe_full;	// @[generators/boom/src/main/scala/util/util.scala:471:27, :473:33, :475:24]
  wire        do_enq = ~full & io_enq_valid;	// @[generators/boom/src/main/scala/util/util.scala:475:24, :505:19, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg         casez_tmp_1;	// @[generators/boom/src/main/scala/util/util.scala:477:42]
  always @(*) begin	// @[generators/boom/src/main/scala/util/util.scala:477:42]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/util/util.scala:477:42, src/main/scala/chisel3/util/Counter.scala:61:40]
      2'b00:
        casez_tmp_1 = valids_0;	// @[generators/boom/src/main/scala/util/util.scala:466:24, :477:42]
      2'b01:
        casez_tmp_1 = valids_1;	// @[generators/boom/src/main/scala/util/util.scala:466:24, :477:42]
      2'b10:
        casez_tmp_1 = valids_2;	// @[generators/boom/src/main/scala/util/util.scala:466:24, :477:42]
      default:
        casez_tmp_1 = valids_3;	// @[generators/boom/src/main/scala/util/util.scala:466:24, :477:42]
    endcase	// @[generators/boom/src/main/scala/util/util.scala:477:42, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg  [7:0]  casez_tmp_2;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  always @(*) begin	// @[generators/boom/src/main/scala/util/util.scala:509:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      2'b00:
        casez_tmp_2 = uops_0_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b01:
        casez_tmp_2 = uops_1_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b10:
        casez_tmp_2 = uops_2_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      default:
        casez_tmp_2 = uops_3_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
    endcase	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  wire [7:0]  out_uop_br_mask = casez_tmp_2;	// @[generators/boom/src/main/scala/util/util.scala:507:17, :509:19]
  reg  [3:0]  casez_tmp_3;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  always @(*) begin	// @[generators/boom/src/main/scala/util/util.scala:509:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      2'b00:
        casez_tmp_3 = uops_0_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b01:
        casez_tmp_3 = uops_1_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b10:
        casez_tmp_3 = uops_2_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      default:
        casez_tmp_3 = uops_3_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
    endcase	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg  [2:0]  casez_tmp_4;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  always @(*) begin	// @[generators/boom/src/main/scala/util/util.scala:509:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      2'b00:
        casez_tmp_4 = uops_0_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b01:
        casez_tmp_4 = uops_1_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b10:
        casez_tmp_4 = uops_2_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      default:
        casez_tmp_4 = uops_3_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
    endcase	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg  [2:0]  casez_tmp_5;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  always @(*) begin	// @[generators/boom/src/main/scala/util/util.scala:509:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      2'b00:
        casez_tmp_5 = uops_0_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b01:
        casez_tmp_5 = uops_1_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b10:
        casez_tmp_5 = uops_2_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      default:
        casez_tmp_5 = uops_3_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
    endcase	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg         casez_tmp_6;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  always @(*) begin	// @[generators/boom/src/main/scala/util/util.scala:509:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      2'b00:
        casez_tmp_6 = uops_0_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b01:
        casez_tmp_6 = uops_1_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b10:
        casez_tmp_6 = uops_2_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      default:
        casez_tmp_6 = uops_3_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
    endcase	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg         casez_tmp_7;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  always @(*) begin	// @[generators/boom/src/main/scala/util/util.scala:509:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      2'b00:
        casez_tmp_7 = uops_0_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b01:
        casez_tmp_7 = uops_1_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b10:
        casez_tmp_7 = uops_2_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      default:
        casez_tmp_7 = uops_3_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
    endcase	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  reg         casez_tmp_8;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  always @(*) begin	// @[generators/boom/src/main/scala/util/util.scala:509:19]
    casez (deq_ptr_value)	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
      2'b00:
        casez_tmp_8 = uops_0_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b01:
        casez_tmp_8 = uops_1_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      2'b10:
        casez_tmp_8 = uops_2_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
      default:
        casez_tmp_8 = uops_3_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20, :509:19]
    endcase	// @[generators/boom/src/main/scala/util/util.scala:509:19, src/main/scala/chisel3/util/Counter.scala:61:40]
  end // always @(*)
  wire        do_deq = (io_deq_ready | ~casez_tmp_1) & ~io_empty;	// @[generators/boom/src/main/scala/util/util.scala:474:25, :477:{39,42,66,69}]
  wire        _GEN = enq_ptr_value == 2'h0;	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        _GEN_0 = do_enq & _GEN;	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_1 = enq_ptr_value == 2'h1;	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        _GEN_2 = do_enq & _GEN_1;	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_3 = enq_ptr_value == 2'h2;	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40]
  wire        _GEN_4 = do_enq & _GEN_3;	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire        _GEN_5 = do_enq & (&enq_ptr_value);	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire [7:0]  _uops_br_mask_T_1 = io_enq_bits_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/util/util.scala:86:{25,27}]
  always @(posedge clock) begin
    if (_GEN_0) begin	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      ram_0_data <= io_enq_bits_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      ram_0_is_hella <= io_enq_bits_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
    end
    if (_GEN_2) begin	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      ram_1_data <= io_enq_bits_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      ram_1_is_hella <= io_enq_bits_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
    end
    if (_GEN_4) begin	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      ram_2_data <= io_enq_bits_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      ram_2_is_hella <= io_enq_bits_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
    end
    if (_GEN_5) begin	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      ram_3_data <= io_enq_bits_data;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
      ram_3_is_hella <= io_enq_bits_is_hella;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
    end
    if (do_enq & _GEN)	// @[generators/boom/src/main/scala/util/util.scala:465:20, :483:22, :488:17, :492:33, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      uops_0_br_mask <= _uops_br_mask_T_1;	// @[generators/boom/src/main/scala/util/util.scala:86:25, :467:20]
    else	// @[generators/boom/src/main/scala/util/util.scala:483:22, :488:17, :492:33]
      uops_0_br_mask <= ({8{~valids_0}} | ~io_brupdate_b1_resolve_mask) & uops_0_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:90:23, :466:24, :467:20, :483:22, :484:23]
    if (_GEN_0) begin	// @[generators/boom/src/main/scala/util/util.scala:465:20, :482:16, :488:17, :490:33]
      uops_0_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_0_ldq_idx <= io_enq_bits_uop_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_0_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_0_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_0_uses_ldq <= io_enq_bits_uop_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_0_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
    end
    if (do_enq & _GEN_1)	// @[generators/boom/src/main/scala/util/util.scala:465:20, :483:22, :488:17, :492:33, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      uops_1_br_mask <= _uops_br_mask_T_1;	// @[generators/boom/src/main/scala/util/util.scala:86:25, :467:20]
    else	// @[generators/boom/src/main/scala/util/util.scala:483:22, :488:17, :492:33]
      uops_1_br_mask <= ({8{~valids_1}} | ~io_brupdate_b1_resolve_mask) & uops_1_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:90:23, :466:24, :467:20, :483:22, :484:23]
    if (_GEN_2) begin	// @[generators/boom/src/main/scala/util/util.scala:465:20, :482:16, :488:17, :490:33]
      uops_1_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_1_ldq_idx <= io_enq_bits_uop_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_1_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_1_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_1_uses_ldq <= io_enq_bits_uop_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_1_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
    end
    if (do_enq & _GEN_3)	// @[generators/boom/src/main/scala/util/util.scala:465:20, :483:22, :488:17, :492:33, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      uops_2_br_mask <= _uops_br_mask_T_1;	// @[generators/boom/src/main/scala/util/util.scala:86:25, :467:20]
    else	// @[generators/boom/src/main/scala/util/util.scala:483:22, :488:17, :492:33]
      uops_2_br_mask <= ({8{~valids_2}} | ~io_brupdate_b1_resolve_mask) & uops_2_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:90:23, :466:24, :467:20, :483:22, :484:23]
    if (_GEN_4) begin	// @[generators/boom/src/main/scala/util/util.scala:465:20, :482:16, :488:17, :490:33]
      uops_2_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_2_ldq_idx <= io_enq_bits_uop_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_2_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_2_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_2_uses_ldq <= io_enq_bits_uop_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_2_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
    end
    if (do_enq & (&enq_ptr_value))	// @[generators/boom/src/main/scala/util/util.scala:465:20, :483:22, :488:17, :492:33, src/main/scala/chisel3/util/Counter.scala:61:40, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      uops_3_br_mask <= _uops_br_mask_T_1;	// @[generators/boom/src/main/scala/util/util.scala:86:25, :467:20]
    else	// @[generators/boom/src/main/scala/util/util.scala:483:22, :488:17, :492:33]
      uops_3_br_mask <= ({8{~valids_3}} | ~io_brupdate_b1_resolve_mask) & uops_3_br_mask;	// @[generators/boom/src/main/scala/util/util.scala:90:23, :466:24, :467:20, :483:22, :484:23]
    if (_GEN_5) begin	// @[generators/boom/src/main/scala/util/util.scala:465:20, :482:16, :488:17, :490:33]
      uops_3_rob_idx <= io_enq_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_3_ldq_idx <= io_enq_bits_uop_ldq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_3_stq_idx <= io_enq_bits_uop_stq_idx;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_3_is_amo <= io_enq_bits_uop_is_amo;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_3_uses_ldq <= io_enq_bits_uop_uses_ldq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
      uops_3_uses_stq <= io_enq_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/util/util.scala:467:20]
    end
    if (reset) begin
      valids_0 <= 1'h0;	// @[generators/boom/src/main/scala/util/util.scala:466:24]
      valids_1 <= 1'h0;	// @[generators/boom/src/main/scala/util/util.scala:466:24]
      valids_2 <= 1'h0;	// @[generators/boom/src/main/scala/util/util.scala:466:24]
      valids_3 <= 1'h0;	// @[generators/boom/src/main/scala/util/util.scala:466:24]
      enq_ptr_value <= 2'h0;	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40]
      deq_ptr_value <= 2'h0;	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40]
      maybe_full <= 1'h0;	// @[generators/boom/src/main/scala/util/util.scala:471:27]
    end
    else begin
      valids_0 <= ~(do_deq & deq_ptr_value == 2'h0) & (_GEN_0 | valids_0 & (io_brupdate_b1_mispredict_mask & uops_0_br_mask) == 8'h0 & ~(io_flush & uops_0_uses_ldq));	// @[generators/boom/src/main/scala/util/util.scala:119:{51,59}, :465:20, :466:24, :467:20, :477:66, :482:{16,69,72,83}, :488:17, :490:33, :496:17, :497:27, src/main/scala/chisel3/util/Counter.scala:61:40]
      valids_1 <= ~(do_deq & deq_ptr_value == 2'h1) & (_GEN_2 | valids_1 & (io_brupdate_b1_mispredict_mask & uops_1_br_mask) == 8'h0 & ~(io_flush & uops_1_uses_ldq));	// @[generators/boom/src/main/scala/util/util.scala:119:{51,59}, :465:20, :466:24, :467:20, :477:66, :482:{16,69,72,83}, :488:17, :490:33, :496:17, :497:27, src/main/scala/chisel3/util/Counter.scala:61:40]
      valids_2 <= ~(do_deq & deq_ptr_value == 2'h2) & (_GEN_4 | valids_2 & (io_brupdate_b1_mispredict_mask & uops_2_br_mask) == 8'h0 & ~(io_flush & uops_2_uses_ldq));	// @[generators/boom/src/main/scala/util/util.scala:119:{51,59}, :465:20, :466:24, :467:20, :477:66, :482:{16,69,72,83}, :488:17, :490:33, :496:17, :497:27, src/main/scala/chisel3/util/Counter.scala:61:40]
      valids_3 <= ~(do_deq & (&deq_ptr_value)) & (_GEN_5 | valids_3 & (io_brupdate_b1_mispredict_mask & uops_3_br_mask) == 8'h0 & ~(io_flush & uops_3_uses_ldq));	// @[generators/boom/src/main/scala/util/util.scala:119:{51,59}, :465:20, :466:24, :467:20, :477:66, :482:{16,69,72,83}, :488:17, :490:33, :496:17, :497:27, src/main/scala/chisel3/util/Counter.scala:61:40]
      if (do_enq)	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
        enq_ptr_value <= enq_ptr_value + 2'h1;	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (do_deq)	// @[generators/boom/src/main/scala/util/util.scala:477:66]
        deq_ptr_value <= deq_ptr_value + 2'h1;	// @[generators/boom/src/main/scala/util/util.scala:465:20, src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      if (~(do_enq == do_deq))	// @[generators/boom/src/main/scala/util/util.scala:471:27, :477:66, :501:{16,28}, :502:16, src/main/scala/chisel3/util/Decoupled.scala:52:35]
        maybe_full <= do_enq;	// @[generators/boom/src/main/scala/util/util.scala:471:27, src/main/scala/chisel3/util/Decoupled.scala:52:35]
    end
  end // always @(posedge)
  assign io_enq_ready = ~full;	// @[generators/boom/src/main/scala/util/util.scala:475:24, :505:19]
  assign io_deq_valid = ~io_empty & casez_tmp_1 & (io_brupdate_b1_mispredict_mask & out_uop_br_mask) == 8'h0 & ~(io_flush & casez_tmp_7);	// @[generators/boom/src/main/scala/util/util.scala:119:{51,59}, :474:25, :477:{42,69}, :507:17, :509:19, :510:{108,111,122}]
  assign io_deq_bits_uop_br_mask = out_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/util/util.scala:86:{25,27}, :507:17]
  assign io_deq_bits_uop_rob_idx = casez_tmp_3;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  assign io_deq_bits_uop_ldq_idx = casez_tmp_4;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  assign io_deq_bits_uop_stq_idx = casez_tmp_5;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  assign io_deq_bits_uop_is_amo = casez_tmp_6;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  assign io_deq_bits_uop_uses_ldq = casez_tmp_7;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  assign io_deq_bits_uop_uses_stq = casez_tmp_8;	// @[generators/boom/src/main/scala/util/util.scala:509:19]
  assign io_deq_bits_data = casez_tmp;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
  assign io_deq_bits_is_hella = casez_tmp_0;	// @[generators/boom/src/main/scala/util/util.scala:465:20]
endmodule

