// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BranchMaskGenerationLogic(
  input        clock,
               reset,
               io_is_branch_0,	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
               io_will_fire_0,	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
  output [2:0] io_br_tag_0,	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
  output [7:0] io_br_mask_0,	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
  output       io_is_full_0,	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
  input  [7:0] io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
               io_brupdate_b2_uop_br_mask,	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
  input        io_brupdate_b2_mispredict,	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
               io_flush_pipeline	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
);

  reg [7:0] branch_mask;	// @[generators/boom/src/main/scala/exu/decode.scala:778:28]
  always @(posedge clock) begin
    if (reset)
      branch_mask <= 8'h0;	// @[generators/boom/src/main/scala/exu/decode.scala:778:28]
    else if (io_flush_pipeline)	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
      branch_mask <= 8'h0;	// @[generators/boom/src/main/scala/exu/decode.scala:778:28]
    else	// @[generators/boom/src/main/scala/exu/decode.scala:756:14]
      branch_mask <= ({8{io_will_fire_0}} & (branch_mask[0] ? (branch_mask[1] ? (branch_mask[2] ? (branch_mask[3] ? (branch_mask[4] ? (branch_mask[5] ? (branch_mask[6] ? {~(branch_mask[7]), 7'h0} : 8'h40) : 8'h20) : 8'h10) : 8'h8) : 8'h4) : 8'h2) : 8'h1) | branch_mask) & ~io_brupdate_b1_resolve_mask & (io_brupdate_b2_mispredict ? io_brupdate_b2_uop_br_mask : 8'hFF);	// @[generators/boom/src/main/scala/exu/decode.scala:778:28, :788:41, :793:18, :796:{13,27,32}, :798:{22,30}, :813:20, :822:19, :825:57, generators/boom/src/main/scala/util/util.scala:90:23]
  end // always @(posedge)
  assign io_br_tag_0 = branch_mask[0] ? (branch_mask[1] ? (branch_mask[2] ? (branch_mask[3] ? (branch_mask[4] ? (branch_mask[5] ? (branch_mask[6] ? {3{~(branch_mask[7])}} : 3'h6) : 3'h5) : 3'h4) : 3'h3) : 3'h2) : 3'h1) : 3'h0;	// @[generators/boom/src/main/scala/exu/decode.scala:778:28, :792:16, :796:{13,27,32}, :797:20]
  assign io_br_mask_0 = branch_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/exu/decode.scala:778:28, generators/boom/src/main/scala/util/util.scala:90:{21,23}]
  assign io_is_full_0 = (&branch_mask) & io_is_branch_0;	// @[generators/boom/src/main/scala/exu/decode.scala:778:28, :788:{37,63}]
endmodule

