// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module DivUnit(
  input         clock,
                reset,
  output        io_req_ready,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input         io_req_valid,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input  [3:0]  io_req_bits_uop_ctrl_op_fcn,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input         io_req_bits_uop_ctrl_fcn_dw,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input  [7:0]  io_req_bits_uop_br_mask,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input  [3:0]  io_req_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input  [5:0]  io_req_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input         io_req_bits_uop_bypassable,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
                io_req_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
                io_req_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input  [1:0]  io_req_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input  [63:0] io_req_bits_rs1_data,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
                io_req_bits_rs2_data,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input         io_req_bits_kill,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
                io_resp_ready,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  output        io_resp_valid,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  output [7:0]  io_resp_bits_uop_br_mask,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  output [3:0]  io_resp_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  output [5:0]  io_resp_bits_uop_pdst,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  output        io_resp_bits_uop_bypassable,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
                io_resp_bits_uop_is_amo,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
                io_resp_bits_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  output [1:0]  io_resp_bits_uop_dst_rtype,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  output [63:0] io_resp_bits_data,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
  input  [7:0]  io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
                io_brupdate_b1_mispredict_mask	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:169:14]
);

  wire       _div_io_req_ready;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:721:19]
  wire       _div_io_resp_valid;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:721:19]
  reg  [7:0] r_uop_br_mask;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  reg  [3:0] r_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  reg  [5:0] r_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  reg        r_uop_bypassable;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  reg        r_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  reg        r_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  reg  [1:0] r_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  wire       _GEN = _div_io_req_ready & io_req_valid;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:721:19, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire       do_kill = _GEN ? (|(io_brupdate_b1_mispredict_mask & io_req_bits_uop_br_mask)) | io_req_bits_kill : (|(io_brupdate_b1_mispredict_mask & r_uop_br_mask)) | io_req_bits_kill;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18, :695:22, :697:{13,63}, :701:{13,53}, generators/boom/src/main/scala/util/util.scala:119:{51,59}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  always @(posedge clock) begin
    if (_GEN) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      r_uop_br_mask <= io_req_bits_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18, generators/boom/src/main/scala/util/util.scala:86:{25,27}]
      r_uop_rob_idx <= io_req_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
      r_uop_pdst <= io_req_bits_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
      r_uop_bypassable <= io_req_bits_uop_bypassable;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
      r_uop_is_amo <= io_req_bits_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
      r_uop_uses_stq <= io_req_bits_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
      r_uop_dst_rtype <= io_req_bits_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
    end
    else	// @[src/main/scala/chisel3/util/Decoupled.scala:52:35]
      r_uop_br_mask <= r_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18, generators/boom/src/main/scala/util/util.scala:86:{25,27}]
  end // always @(posedge)
  MulDiv div (	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:721:19]
    .clock             (clock),
    .reset             (reset),
    .io_req_ready      (_div_io_req_ready),
    .io_req_valid      (io_req_valid & ~do_kill),	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:695:22, :697:13, :701:13, :725:{39,42}]
    .io_req_bits_fn    (io_req_bits_uop_ctrl_op_fcn),
    .io_req_bits_dw    (io_req_bits_uop_ctrl_fcn_dw),
    .io_req_bits_in1   (io_req_bits_rs1_data),
    .io_req_bits_in2   (io_req_bits_rs2_data),
    .io_kill           (do_kill),	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:695:22, :697:13, :701:13]
    .io_resp_ready     (io_resp_ready),
    .io_resp_valid     (_div_io_resp_valid),
    .io_resp_bits_data (io_resp_bits_data)
  );
  assign io_req_ready = _div_io_req_ready;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:721:19]
  assign io_resp_valid = _div_io_resp_valid & ~do_kill;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:695:22, :697:13, :701:13, :721:19, :725:42, :737:44]
  assign io_resp_bits_uop_br_mask = r_uop_br_mask;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  assign io_resp_bits_uop_rob_idx = r_uop_rob_idx;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  assign io_resp_bits_uop_pdst = r_uop_pdst;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  assign io_resp_bits_uop_bypassable = r_uop_bypassable;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  assign io_resp_bits_uop_is_amo = r_uop_is_amo;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  assign io_resp_bits_uop_uses_stq = r_uop_uses_stq;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
  assign io_resp_bits_uop_dst_rtype = r_uop_dst_rtype;	// @[generators/boom/src/main/scala/exu/execution-units/functional-unit.scala:690:18]
endmodule

