// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FPToInt(
  input         clock,
                io_in_valid,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
                io_in_bits_ren2,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
  input  [1:0]  io_in_bits_typeTagOut,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
  input         io_in_bits_wflags,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
  input  [2:0]  io_in_bits_rm,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
  input  [1:0]  io_in_bits_typ,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
                io_in_bits_fmt,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
  input  [64:0] io_in_bits_in1,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
                io_in_bits_in2,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
  output        io_out_bits_lt,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
  output [63:0] io_out_bits_toint,	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
  output [4:0]  io_out_bits_exc	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
);

  wire [63:0] toint;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:477:19, :483:20, :488:21]
  wire        _narrow_io_signedOut_T;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:494:35]
  wire        intType;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:477:19, :483:20, :488:21]
  wire [2:0]  _narrow_io_intExceptionFlags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:501:30]
  wire [63:0] _conv_io_out;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:491:24]
  wire [2:0]  _conv_io_intExceptionFlags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:491:24]
  wire        _dcmp_io_lt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:463:20]
  wire        _dcmp_io_eq;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:463:20]
  wire [4:0]  _dcmp_io_exceptionFlags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:463:20]
  reg         in_ren2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  reg  [1:0]  in_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  reg         in_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  reg  [2:0]  in_rm;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  reg  [1:0]  in_typ;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  reg  [1:0]  in_fmt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  reg  [64:0] in_in1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  reg  [64:0] in_in2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  wire [12:0] store_unrecoded_rawIn_sExp = {1'h0, in_in1[63:52]};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :60:27, generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21, :517:53]
  wire [52:0] _store_unrecoded_denormFract_T_1 = {1'h0, |(in_in1[63:61]), in_in1[51:1]} >> 6'h1 - in_in1[57:52];	// @[generators/hardfloat/hardfloat/src/main/scala/fNFromRecFN.scala:52:{35,47}, :53:{38,42}, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21, :517:53]
  wire [1:0]  _store_prevUnrecoded_rawIn_isSpecial_T = {in_in1[52], in_in1[30]};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:28, generators/rocket-chip/src/main/scala/tile/FPU.scala:437:10, :460:21]
  wire        store_prevUnrecoded_rawIn_isInf = (&_store_prevUnrecoded_rawIn_isSpecial_T) & ~(in_in1[29]);	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}, generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  wire        store_prevUnrecoded_isSubnormal = $signed({1'h0, in_in1[52], in_in1[30:23]}) < 10'sh82;	// @[generators/hardfloat/hardfloat/src/main/scala/fNFromRecFN.scala:51:38, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :60:27, generators/rocket-chip/src/main/scala/tile/FPU.scala:437:10, :460:21, :517:53]
  wire [23:0] _store_prevUnrecoded_denormFract_T_1 = {1'h0, |{in_in1[52], in_in1[30:29]}, in_in1[22:1]} >> 5'h1 - in_in1[27:23];	// @[generators/hardfloat/hardfloat/src/main/scala/fNFromRecFN.scala:52:{35,47}, :53:{38,42}, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, generators/rocket-chip/src/main/scala/tile/FPU.scala:437:10, :460:21, :517:53]
  wire        store_unrecoded_rawIn_1_isInf = (&(in_in1[63:62])) & ~(in_in1[61]);	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}, generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  wire        store_unrecoded_isSubnormal_1 = $signed(store_unrecoded_rawIn_sExp) < 13'sh402;	// @[generators/hardfloat/hardfloat/src/main/scala/fNFromRecFN.scala:51:38, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:60:27]
  wire [52:0] _store_unrecoded_denormFract_T_3 = {1'h0, |(in_in1[63:61]), in_in1[51:1]} >> 6'h1 - in_in1[57:52];	// @[generators/hardfloat/hardfloat/src/main/scala/fNFromRecFN.scala:52:{35,47}, :53:{38,42}, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21, :517:53]
  wire [51:0] store_unrecoded_fractOut_1 = store_unrecoded_isSubnormal_1 ? _store_unrecoded_denormFract_T_3[51:0] : store_unrecoded_rawIn_1_isInf ? 52'h0 : in_in1[51:0];	// @[generators/hardfloat/hardfloat/src/main/scala/fNFromRecFN.scala:51:38, :53:{42,60}, :62:16, :64:20, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:57:33, :61:49, generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  wire [1:0]  _store_prevUnrecoded_rawIn_isSpecial_T_1 = {in_in1[52], in_in1[30]};	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:28, generators/rocket-chip/src/main/scala/tile/FPU.scala:437:10, :460:21]
  wire        store_prevUnrecoded_rawIn_1_isInf = (&_store_prevUnrecoded_rawIn_isSpecial_T_1) & ~(in_in1[29]);	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:41, :57:{33,36}, generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
  wire        store_prevUnrecoded_isSubnormal_1 = $signed({1'h0, in_in1[52], in_in1[30:23]}) < 10'sh82;	// @[generators/hardfloat/hardfloat/src/main/scala/fNFromRecFN.scala:51:38, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :60:27, generators/rocket-chip/src/main/scala/tile/FPU.scala:437:10, :460:21, :517:53]
  wire [23:0] _store_prevUnrecoded_denormFract_T_3 = {1'h0, |{in_in1[52], in_in1[30:29]}, in_in1[22:1]} >> 5'h1 - in_in1[27:23];	// @[generators/hardfloat/hardfloat/src/main/scala/fNFromRecFN.scala:52:{35,47}, :53:{38,42}, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :52:{28,53}, generators/rocket-chip/src/main/scala/tile/FPU.scala:437:10, :460:21, :517:53]
  wire [63:0] store = in_typeTagOut[0] ? {in_in1[64], (store_unrecoded_isSubnormal_1 ? 11'h0 : in_in1[62:52] + 11'h3FF) | {11{(&(in_in1[63:62])) & in_in1[61] | store_unrecoded_rawIn_1_isInf}}, store_unrecoded_fractOut_1[51:32], (&(in_in1[63:61])) ? {in_in1[31], (store_prevUnrecoded_isSubnormal_1 ? 8'h0 : in_in1[30:23] + 8'h7F) | {8{(&_store_prevUnrecoded_rawIn_isSpecial_T_1) & in_in1[29] | store_prevUnrecoded_rawIn_1_isInf}}, store_prevUnrecoded_isSubnormal_1 ? _store_prevUnrecoded_denormFract_T_3[22:0] : store_prevUnrecoded_rawIn_1_isInf ? 23'h0 : in_in1[22:0]} : store_unrecoded_fractOut_1[31:0]} : {2{(&(in_in1[63:61])) ? {in_in1[31], (store_prevUnrecoded_isSubnormal ? 8'h0 : in_in1[30:23] + 8'h7F) | {8{(&_store_prevUnrecoded_rawIn_isSpecial_T) & in_in1[29] | store_prevUnrecoded_rawIn_isInf}}, store_prevUnrecoded_isSubnormal ? _store_prevUnrecoded_denormFract_T_1[22:0] : store_prevUnrecoded_rawIn_isInf ? 23'h0 : in_in1[22:0]} : $signed(store_unrecoded_rawIn_sExp) < 13'sh402 ? _store_unrecoded_denormFract_T_1[31:0] : (&(in_in1[63:62])) & ~(in_in1[61]) ? 32'h0 : in_in1[31:0]}};	// @[generators/hardfloat/hardfloat/src/main/scala/fNFromRecFN.scala:51:38, :53:{42,60}, :56:16, :58:{27,45}, :60:{15,21,44}, :62:16, :64:20, :66:12, generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, :53:{28,53}, :56:{33,41}, :57:{33,36}, :59:25, :60:27, :61:49, generators/rocket-chip/src/main/scala/tile/FPU.scala:243:{25,56}, :436:10, :440:{10,21,44,81}, :460:21, :470:58, generators/rocket-chip/src/main/scala/util/package.scala:32:47, :33:76]
  wire [8:0]  _classify_out_expOut_commonCase_T = in_in1[60:52] - 9'h100;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, generators/rocket-chip/src/main/scala/tile/FPU.scala:274:31, :460:21]
  wire [8:0]  classify_out_expOut = in_in1[63:61] == 3'h0 | in_in1[63:61] > 3'h5 ? {in_in1[63:61], _classify_out_expOut_commonCase_T[5:0]} : _classify_out_expOut_commonCase_T;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:51:21, generators/rocket-chip/src/main/scala/tile/FPU.scala:273:26, :274:{31,50}, :275:{10,19,27,38,49,69}, :460:21, :496:29]
  wire        classify_out_isHighSubnormalIn = classify_out_expOut[6:0] < 7'h2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:252:{30,55}, :275:10]
  wire        _classify_out_isNormal_T = classify_out_expOut[8:7] == 2'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:248:17, :249:22, :253:46, :275:10]
  wire        classify_out_isSubnormal = classify_out_expOut[8:6] == 3'h1 | _classify_out_isNormal_T & classify_out_isHighSubnormalIn;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:248:17, :252:55, :253:{28,36,46,54}, :275:10]
  wire        classify_out_isNormal = _classify_out_isNormal_T & ~classify_out_isHighSubnormalIn | classify_out_expOut[8:7] == 2'h2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:248:17, :249:22, :252:55, :253:46, :254:{35,38,57,67}, :275:10]
  wire        classify_out_isZero = classify_out_expOut[8:6] == 3'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:248:17, :255:23, :275:10, :496:29]
  wire        classify_out_isInf = (&(classify_out_expOut[8:7])) & ~(classify_out_expOut[6]);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:248:17, :249:22, :250:28, :256:{27,30,35}, :275:10]
  wire        classify_out_isHighSubnormalIn_1 = in_in1[61:52] < 10'h2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:252:{30,55}, :460:21]
  wire        _classify_out_isNormal_T_4 = in_in1[63:62] == 2'h1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:243:25, :249:22, :253:46, :460:21]
  wire        classify_out_isSubnormal_1 = in_in1[63:61] == 3'h1 | _classify_out_isNormal_T_4 & classify_out_isHighSubnormalIn_1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:243:25, :252:55, :253:{28,36,46,54}, :460:21]
  wire        classify_out_isNormal_1 = _classify_out_isNormal_T_4 & ~classify_out_isHighSubnormalIn_1 | in_in1[63:62] == 2'h2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:243:25, :249:22, :252:55, :253:46, :254:{35,38,57,67}, :460:21]
  wire        classify_out_isZero_1 = in_in1[63:61] == 3'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:243:25, :255:23, :460:21, :496:29]
  wire        classify_out_isInf_1 = (&(in_in1[63:62])) & ~(in_in1[61]);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:243:25, :249:22, :250:28, :256:{27,30,35}, :460:21]
  assign intType = in_wflags ? ~in_ren2 & in_typ[1] : ~(in_rm[0]) & in_fmt[0];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21, :472:{28,35}, :477:{14,19}, :480:13, :483:20, :486:13, :488:{11,21}, :490:15, generators/rocket-chip/src/main/scala/util/package.scala:155:13]
  assign _narrow_io_signedOut_T = in_typ[0];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21, :494:35]
  wire        excSign = in_in1[64] & in_in1[63:61] != 3'h7;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:59:25, generators/rocket-chip/src/main/scala/tile/FPU.scala:243:{25,56}, :460:21, :506:59]
  wire        invalid = _conv_io_intExceptionFlags[2] | _narrow_io_intExceptionFlags[1];	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:491:24, :501:30, :508:{50,54,84}]
  assign toint = in_wflags ? (in_ren2 ? {store[63:32], 31'h0, |(~(in_rm[1:0]) & {_dcmp_io_lt, _dcmp_io_eq})} : ~(in_typ[1]) & invalid ? {_conv_io_out[63:32], ~_narrow_io_signedOut_T == excSign, {31{~excSign}}} : _conv_io_out) : in_rm[0] ? {store[63:32], 22'h0, in_typeTagOut[0] ? {(&(in_in1[63:61])) & in_in1[51], (&(in_in1[63:61])) & ~(in_in1[51]), classify_out_isInf_1 & ~(in_in1[64]), classify_out_isNormal_1 & ~(in_in1[64]), classify_out_isSubnormal_1 & ~(in_in1[64]), classify_out_isZero_1 & ~(in_in1[64]), classify_out_isZero_1 & in_in1[64], classify_out_isSubnormal_1 & in_in1[64], classify_out_isNormal_1 & in_in1[64], classify_out_isInf_1 & in_in1[64]} : {(&(classify_out_expOut[8:6])) & in_in1[51], (&(classify_out_expOut[8:6])) & ~(in_in1[51]), classify_out_isInf & ~(in_in1[64]), classify_out_isNormal & ~(in_in1[64]), classify_out_isSubnormal & ~(in_in1[64]), classify_out_isZero & ~(in_in1[64]), classify_out_isZero & in_in1[64], classify_out_isSubnormal & in_in1[64], classify_out_isNormal & in_in1[64], classify_out_isInf & in_in1[64]}} : store;	// @[generators/hardfloat/hardfloat/src/main/scala/rawFloatFromRecFN.scala:59:25, generators/rocket-chip/src/main/scala/tile/FPU.scala:243:25, :248:17, :253:36, :254:57, :255:23, :256:27, :257:22, :258:{24,27,29}, :259:24, :261:{8,31,34,50}, :262:{21,38,55}, :263:{21,39,54}, :275:10, :460:21, :463:20, :471:26, :477:{14,19}, :479:{11,27,36}, :483:20, :484:{11,15,22,27,53,57,66}, :488:21, :491:24, :494:{28,35}, :495:13, :500:{23,32}, :506:59, :507:{46,63,69}, :508:54, :509:{26,34,40,53}, generators/rocket-chip/src/main/scala/util/package.scala:32:47, :33:76, :155:13]
  always @(posedge clock) begin
    if (io_in_valid) begin	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:455:14]
      in_ren2 <= io_in_bits_ren2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
      in_typeTagOut <= io_in_bits_typeTagOut;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
      in_wflags <= io_in_bits_wflags;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
      in_rm <= io_in_bits_rm;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
      in_typ <= io_in_bits_typ;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
      in_fmt <= io_in_bits_fmt;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
      in_in1 <= io_in_bits_in1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
      in_in2 <= io_in_bits_in2;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
    end
  end // always @(posedge)
  CompareRecFN dcmp (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:463:20]
    .io_a              (in_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
    .io_b              (in_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
    .io_signaling      (~(in_rm[1])),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21, :466:{24,30}]
    .io_lt             (_dcmp_io_lt),
    .io_eq             (_dcmp_io_eq),
    .io_exceptionFlags (_dcmp_io_exceptionFlags)
  );
  RecFNToIN conv (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:491:24]
    .io_in                (in_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
    .io_roundingMode      (in_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
    .io_signedOut         (~_narrow_io_signedOut_T),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:494:{28,35}]
    .io_out               (_conv_io_out),
    .io_intExceptionFlags (_conv_io_intExceptionFlags)
  );
  RecFNToIN_1 narrow (	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:501:30]
    .io_in                (in_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
    .io_roundingMode      (in_rm),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21]
    .io_signedOut         (~_narrow_io_signedOut_T),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:494:35, :504:34]
    .io_intExceptionFlags (_narrow_io_intExceptionFlags)
  );
  assign io_out_bits_lt = _dcmp_io_lt | $signed(in_in1) < 65'sh0 & $signed(in_in2) > -65'sh1;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21, :463:20, :517:{32,53,59,79}]
  assign io_out_bits_toint = intType ? toint : {{32{toint[31]}}, toint[31:0]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:474:59, :477:19, :483:20, :488:21, generators/rocket-chip/src/main/scala/util/package.scala:33:76, :124:{15,20,38}]
  assign io_out_bits_exc = in_wflags ? (in_ren2 ? _dcmp_io_exceptionFlags : in_typ[1] ? {|(_conv_io_intExceptionFlags[2:1]), 3'h0, _conv_io_intExceptionFlags[0]} : {invalid, 3'h0, ~invalid & _conv_io_intExceptionFlags[0]}) : 5'h0;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:460:21, :463:20, :475:19, :483:20, :485:21, :488:21, :491:24, :496:{23,29,55,62,102}, :500:32, :508:54, :510:{27,33,53,62}, generators/rocket-chip/src/main/scala/util/package.scala:155:13]
endmodule

