// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FPU(
  input         clock,
                reset,
                io_req_valid,	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:171:14]
  input  [6:0]  io_req_bits_uop_uopc,	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:171:14]
  input  [19:0] io_req_bits_uop_imm_packed,	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:171:14]
  input  [64:0] io_req_bits_rs1_data,	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:171:14]
                io_req_bits_rs2_data,	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:171:14]
                io_req_bits_rs3_data,	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:171:14]
  input  [2:0]  io_req_bits_fcsr_rm,	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:171:14]
  output [64:0] io_resp_bits_data,	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:171:14]
  output        io_resp_bits_fflags_valid,	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:171:14]
  output [4:0]  io_resp_bits_fflags_bits_flags	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:171:14]
);

  wire        _fpmu_io_out_valid;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:224:20]
  wire [64:0] _fpmu_io_out_bits_data;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:224:20]
  wire [4:0]  _fpmu_io_out_bits_exc;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:224:20]
  wire        _fpiu_io_out_bits_lt;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:215:20]
  wire [63:0] _fpiu_io_out_bits_toint;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:215:20]
  wire [4:0]  _fpiu_io_out_bits_exc;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:215:20]
  wire [1:0]  _sfma_io_in_bits_fma_decoder_io_cmd;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:201:29]
  wire        _sfma_io_out_valid;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:211:20]
  wire [64:0] _sfma_io_out_bits_data;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:211:20]
  wire [4:0]  _sfma_io_out_bits_exc;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:211:20]
  wire [1:0]  _dfma_io_in_bits_fma_decoder_io_cmd;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:201:29]
  wire        _dfma_io_out_valid;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:207:20]
  wire [64:0] _dfma_io_out_bits_data;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:207:20]
  wire [4:0]  _dfma_io_out_bits_exc;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:207:20]
  wire        _fp_decoder_io_sigs_ren2;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
  wire        _fp_decoder_io_sigs_ren3;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
  wire        _fp_decoder_io_sigs_swap23;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
  wire [1:0]  _fp_decoder_io_sigs_typeTagIn;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
  wire [1:0]  _fp_decoder_io_sigs_typeTagOut;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
  wire        _fp_decoder_io_sigs_toint;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
  wire        _fp_decoder_io_sigs_fastpipe;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
  wire        _fp_decoder_io_sigs_fma;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
  wire        _fp_decoder_io_sigs_wflags;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
  wire [2:0]  fp_rm = (&(io_req_bits_uop_imm_packed[2:0])) ? io_req_bits_fcsr_rm : io_req_bits_uop_imm_packed[2:0];	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:184:{18,51}, generators/boom/src/main/scala/util/util.scala:290:58]
  wire        _sfma_io_in_valid_T = io_req_valid & _fp_decoder_io_sigs_fma;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26, :208:36]
  wire        _fpmu_double_T_1 = _fp_decoder_io_sigs_typeTagOut == 2'h1;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26, :208:74]
  wire [32:0] _sfma_io_in_bits_req_in2_T_1 = {io_req_bits_rs2_data[31], io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:0]} | ((&(io_req_bits_rs2_data[64:60])) ? 33'h0 : 33'hE0400000);	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:326:{49,84}, :350:31, :351:14, :352:14, :353:14, :366:{26,31}]
  wire        _fpiu_io_in_valid_T_2 = io_req_valid & (_fp_decoder_io_sigs_toint | _fp_decoder_io_sigs_fastpipe & _fp_decoder_io_sigs_wflags);	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26, :216:{36,54,75}]
  wire [2:0]  fpiu_io_in_bits_req_in1_expOut_expCode = {io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:29]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:270:18, :273:26, :352:14]
  wire [11:0] _fpiu_io_in_bits_req_in1_expOut_commonCase_T_2 = {3'h0, io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:23]} + 12'h700;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:270:18, :274:{31,50}, :275:19, :352:14]
  wire [64:0] fpiu_io_in_bits_req_in1 = _fp_decoder_io_sigs_typeTagIn[0] | (&(io_req_bits_rs1_data[64:60])) ? (_fp_decoder_io_sigs_typeTagIn[0] ? io_req_bits_rs1_data : {io_req_bits_rs1_data[31], fpiu_io_in_bits_req_in1_expOut_expCode == 3'h0 | fpiu_io_in_bits_req_in1_expOut_expCode > 3'h5 ? {io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:29], _fpiu_io_in_bits_req_in1_expOut_commonCase_T_2[8:0]} : _fpiu_io_in_bits_req_in1_expOut_commonCase_T_2, io_req_bits_rs1_data[22:0], 29'h0}) : 65'hE008000000000000;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26, generators/rocket-chip/src/main/scala/tile/FPU.scala:269:20, :270:18, :271:38, :273:26, :274:50, :275:{10,19,27,38,49,69}, :277:8, :326:{49,84}, :351:14, :352:14, :363:10, :366:31, generators/rocket-chip/src/main/scala/util/package.scala:32:47, :33:76]
  wire [2:0]  fpiu_io_in_bits_req_in2_expOut_expCode = {io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:29]};	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:270:18, :273:26, :352:14]
  wire [11:0] _fpiu_io_in_bits_req_in2_expOut_commonCase_T_2 = {3'h0, io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:23]} + 12'h700;	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:270:18, :274:{31,50}, :275:19, :352:14]
  wire [64:0] fpiu_io_in_bits_req_in2 = _fp_decoder_io_sigs_typeTagIn[0] | (&(io_req_bits_rs2_data[64:60])) ? (_fp_decoder_io_sigs_typeTagIn[0] ? io_req_bits_rs2_data : {io_req_bits_rs2_data[31], fpiu_io_in_bits_req_in2_expOut_expCode == 3'h0 | fpiu_io_in_bits_req_in2_expOut_expCode > 3'h5 ? {io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:29], _fpiu_io_in_bits_req_in2_expOut_commonCase_T_2[8:0]} : _fpiu_io_in_bits_req_in2_expOut_commonCase_T_2, io_req_bits_rs2_data[22:0], 29'h0}) : 65'hE008000000000000;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26, generators/rocket-chip/src/main/scala/tile/FPU.scala:269:20, :270:18, :271:38, :273:26, :274:50, :275:{10,19,27,38,49,69}, :277:8, :326:{49,84}, :351:14, :352:14, :363:10, :366:31, generators/rocket-chip/src/main/scala/util/package.scala:32:47, :33:76]
  reg         fpiu_out_REG;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:218:30]
  reg         fpiu_out_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
  reg  [63:0] fpiu_out_pipe_b_toint;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
  reg  [4:0]  fpiu_out_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
  reg         fpiu_out_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
  reg  [63:0] fpiu_out_pipe_pipe_b_toint;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
  reg  [4:0]  fpiu_out_pipe_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
  reg         fpiu_out_pipe_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
  reg  [63:0] fpiu_out_pipe_pipe_pipe_b_toint;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
  reg  [4:0]  fpiu_out_pipe_pipe_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
  wire        _fpmu_double_T = io_req_valid & _fp_decoder_io_sigs_fastpipe;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26, :225:36]
  reg         fpmu_double_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
  reg         fpmu_double_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
  reg         fpmu_double_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
  reg         fpmu_double_pipe_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
  reg         fpmu_double_pipe_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
  reg         fpmu_double_pipe_pipe_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
  reg         fpmu_double_pipe_pipe_pipe_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
  always @(posedge clock) begin
    fpiu_out_REG <= _fpiu_io_in_valid_T_2 & ~_fp_decoder_io_sigs_fastpipe;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26, :216:36, :218:{30,48,51}]
    if (fpiu_out_REG) begin	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:218:30]
      fpiu_out_pipe_b_toint <= _fpiu_io_out_bits_toint;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:215:20, src/main/scala/chisel3/util/Valid.scala:130:26]
      fpiu_out_pipe_b_exc <= _fpiu_io_out_bits_exc;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:215:20, src/main/scala/chisel3/util/Valid.scala:130:26]
    end
    if (fpiu_out_pipe_v) begin	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
      fpiu_out_pipe_pipe_b_toint <= fpiu_out_pipe_b_toint;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
      fpiu_out_pipe_pipe_b_exc <= fpiu_out_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
    end
    if (fpiu_out_pipe_pipe_v) begin	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
      fpiu_out_pipe_pipe_pipe_b_toint <= fpiu_out_pipe_pipe_b_toint;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
      fpiu_out_pipe_pipe_pipe_b_exc <= fpiu_out_pipe_pipe_b_exc;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
    end
    if (_fpmu_double_T)	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:225:36]
      fpmu_double_pipe_b <= _fpmu_double_T_1;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:208:74, src/main/scala/chisel3/util/Valid.scala:130:26]
    if (fpmu_double_pipe_v)	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
      fpmu_double_pipe_pipe_b <= fpmu_double_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
    if (fpmu_double_pipe_pipe_v)	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
      fpmu_double_pipe_pipe_pipe_b <= fpmu_double_pipe_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
    if (fpmu_double_pipe_pipe_pipe_v)	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
      fpmu_double_pipe_pipe_pipe_pipe_b <= fpmu_double_pipe_pipe_pipe_b;	// @[src/main/scala/chisel3/util/Valid.scala:130:26]
    if (reset) begin
      fpiu_out_pipe_v <= 1'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:175:16, src/main/scala/chisel3/util/Valid.scala:129:24]
      fpiu_out_pipe_pipe_v <= 1'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:175:16, src/main/scala/chisel3/util/Valid.scala:129:24]
      fpiu_out_pipe_pipe_pipe_v <= 1'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:175:16, src/main/scala/chisel3/util/Valid.scala:129:24]
      fpmu_double_pipe_v <= 1'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:175:16, src/main/scala/chisel3/util/Valid.scala:129:24]
      fpmu_double_pipe_pipe_v <= 1'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:175:16, src/main/scala/chisel3/util/Valid.scala:129:24]
      fpmu_double_pipe_pipe_pipe_v <= 1'h0;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:175:16, src/main/scala/chisel3/util/Valid.scala:129:24]
    end
    else begin
      fpiu_out_pipe_v <= fpiu_out_REG;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:218:30, src/main/scala/chisel3/util/Valid.scala:129:24]
      fpiu_out_pipe_pipe_v <= fpiu_out_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
      fpiu_out_pipe_pipe_pipe_v <= fpiu_out_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
      fpmu_double_pipe_v <= _fpmu_double_T;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:225:36, src/main/scala/chisel3/util/Valid.scala:129:24]
      fpmu_double_pipe_pipe_v <= fpmu_double_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
      fpmu_double_pipe_pipe_pipe_v <= fpmu_double_pipe_pipe_v;	// @[src/main/scala/chisel3/util/Valid.scala:129:24]
    end
  end // always @(posedge)
  UOPCodeFPUDecoder fp_decoder (	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_uopc            (io_req_bits_uop_uopc),
    .io_sigs_ren2       (_fp_decoder_io_sigs_ren2),
    .io_sigs_ren3       (_fp_decoder_io_sigs_ren3),
    .io_sigs_swap23     (_fp_decoder_io_sigs_swap23),
    .io_sigs_typeTagIn  (_fp_decoder_io_sigs_typeTagIn),
    .io_sigs_typeTagOut (_fp_decoder_io_sigs_typeTagOut),
    .io_sigs_fromint    (/* unused */),
    .io_sigs_toint      (_fp_decoder_io_sigs_toint),
    .io_sigs_fastpipe   (_fp_decoder_io_sigs_fastpipe),
    .io_sigs_fma        (_fp_decoder_io_sigs_fma),
    .io_sigs_wflags     (_fp_decoder_io_sigs_wflags)
  );
  FPUFMAPipe dfma (	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:207:20]
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_sfma_io_in_valid_T & _fpmu_double_T_1),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:208:{36,51,74}]
    .io_in_bits_ren3   (_fp_decoder_io_sigs_ren3),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_in_bits_swap23 (_fp_decoder_io_sigs_swap23),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_in_bits_rm     (fp_rm),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:184:18]
    .io_in_bits_fmaCmd (_dfma_io_in_bits_fma_decoder_io_cmd),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:201:29]
    .io_in_bits_in1    (io_req_bits_rs1_data),
    .io_in_bits_in2    (io_req_bits_rs2_data),
    .io_in_bits_in3    (_fp_decoder_io_sigs_swap23 ? io_req_bits_rs2_data : io_req_bits_rs3_data),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26, :193:13, :194:{27,37}]
    .io_out_valid      (_dfma_io_out_valid),
    .io_out_bits_data  (_dfma_io_out_bits_data),
    .io_out_bits_exc   (_dfma_io_out_bits_exc)
  );
  FMADecoder dfma_io_in_bits_fma_decoder (	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:201:29]
    .io_uopc (io_req_bits_uop_uopc),
    .io_cmd  (_dfma_io_in_bits_fma_decoder_io_cmd)
  );
  FPUFMAPipe_1 sfma (	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:211:20]
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_sfma_io_in_valid_T & _fp_decoder_io_sigs_typeTagOut == 2'h0),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:175:16, :181:26, :208:36, :212:{51,74}]
    .io_in_bits_ren3   (_fp_decoder_io_sigs_ren3),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_in_bits_swap23 (_fp_decoder_io_sigs_swap23),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_in_bits_rm     (fp_rm),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:184:18]
    .io_in_bits_fmaCmd (_sfma_io_in_bits_fma_decoder_io_cmd),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:201:29]
    .io_in_bits_in1    ({32'h0, {io_req_bits_rs1_data[31], io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:0]} | ((&(io_req_bits_rs1_data[64:60])) ? 33'h0 : 33'hE0400000)}),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:191:13, generators/rocket-chip/src/main/scala/tile/FPU.scala:326:{49,84}, :350:31, :351:14, :352:14, :353:14, :366:{26,31}]
    .io_in_bits_in2    ({32'h0, _sfma_io_in_bits_req_in2_T_1}),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:191:13, :192:13, generators/rocket-chip/src/main/scala/tile/FPU.scala:366:26]
    .io_in_bits_in3    ({32'h0, _fp_decoder_io_sigs_swap23 ? _sfma_io_in_bits_req_in2_T_1 : {io_req_bits_rs3_data[31], io_req_bits_rs3_data[52], io_req_bits_rs3_data[30:0]} | ((&(io_req_bits_rs3_data[64:60])) ? 33'h0 : 33'hE0400000)}),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26, :191:13, :193:13, :194:{27,37}, generators/rocket-chip/src/main/scala/tile/FPU.scala:326:{49,84}, :350:31, :351:14, :352:14, :353:14, :366:{26,31}]
    .io_out_valid      (_sfma_io_out_valid),
    .io_out_bits_data  (_sfma_io_out_bits_data),
    .io_out_bits_exc   (_sfma_io_out_bits_exc)
  );
  FMADecoder sfma_io_in_bits_fma_decoder (	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:201:29]
    .io_uopc (io_req_bits_uop_uopc),
    .io_cmd  (_sfma_io_in_bits_fma_decoder_io_cmd)
  );
  FPToInt fpiu (	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:215:20]
    .clock                 (clock),
    .io_in_valid           (_fpiu_io_in_valid_T_2),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:216:36]
    .io_in_bits_ren2       (_fp_decoder_io_sigs_ren2),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_in_bits_typeTagOut (_fp_decoder_io_sigs_typeTagOut),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_in_bits_wflags     (_fp_decoder_io_sigs_wflags),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_in_bits_rm         (fp_rm),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:184:18]
    .io_in_bits_typ        (io_req_bits_uop_imm_packed[9:8]),	// @[generators/boom/src/main/scala/util/util.scala:296:59]
    .io_in_bits_fmt        (io_req_bits_uop_uopc == 7'h46 ? 2'h0 : {1'h0, |_fp_decoder_io_sigs_typeTagIn}),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:175:16, :181:26, :196:{13,24}, :197:{27,43}, :198:15]
    .io_in_bits_in1        (fpiu_io_in_bits_req_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:363:10]
    .io_in_bits_in2        (fpiu_io_in_bits_req_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:363:10]
    .io_out_bits_lt        (_fpiu_io_out_bits_lt),
    .io_out_bits_toint     (_fpiu_io_out_bits_toint),
    .io_out_bits_exc       (_fpiu_io_out_bits_exc)
  );
  FPToFP fpmu (	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:224:20]
    .clock                 (clock),
    .reset                 (reset),
    .io_in_valid           (_fpmu_double_T),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:225:36]
    .io_in_bits_ren2       (_fp_decoder_io_sigs_ren2),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_in_bits_typeTagOut (_fp_decoder_io_sigs_typeTagOut),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_in_bits_wflags     (_fp_decoder_io_sigs_wflags),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:181:26]
    .io_in_bits_rm         (fp_rm),	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:184:18]
    .io_in_bits_in1        (fpiu_io_in_bits_req_in1),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:363:10]
    .io_in_bits_in2        (fpiu_io_in_bits_req_in2),	// @[generators/rocket-chip/src/main/scala/tile/FPU.scala:363:10]
    .io_out_valid          (_fpmu_io_out_valid),
    .io_out_bits_data      (_fpmu_io_out_bits_data),
    .io_out_bits_exc       (_fpmu_io_out_bits_exc),
    .io_lt                 (_fpiu_io_out_bits_lt)	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:215:20]
  );
  assign io_resp_bits_data = _dfma_io_out_valid ? _dfma_io_out_bits_data : _sfma_io_out_valid ? {12'hFFF, _sfma_io_out_bits_data[31], 20'hFFFFF, _sfma_io_out_bits_data[32], _sfma_io_out_bits_data[30:0]} : fpiu_out_pipe_pipe_pipe_v ? {1'h0, fpiu_out_pipe_pipe_pipe_b_toint} : fpmu_double_pipe_pipe_pipe_pipe_b ? _fpmu_io_out_bits_data : {12'hFFF, _fpmu_io_out_bits_data[31], 20'hFFFFF, _fpmu_io_out_bits_data[32], _fpmu_io_out_bits_data[30:0]};	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:175:16, :207:20, :211:20, :221:20, :224:20, :236:8, :237:8, :238:8, generators/rocket-chip/src/main/scala/tile/FPU.scala:330:26, :332:42, :334:8, :336:8, :337:8, generators/rocket-chip/src/main/scala/util/package.scala:33:76, src/main/scala/chisel3/util/Valid.scala:129:24, :130:26]
  assign io_resp_bits_fflags_valid = fpiu_out_pipe_pipe_pipe_v | _fpmu_io_out_valid | _sfma_io_out_valid | _dfma_io_out_valid;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:207:20, :211:20, :224:20, :233:38, src/main/scala/chisel3/util/Valid.scala:129:24]
  assign io_resp_bits_fflags_bits_flags = _dfma_io_out_valid ? _dfma_io_out_bits_exc : _sfma_io_out_valid ? _sfma_io_out_bits_exc : fpiu_out_pipe_pipe_pipe_v ? fpiu_out_pipe_pipe_pipe_b_exc : _fpmu_io_out_bits_exc;	// @[generators/boom/src/main/scala/exu/execution-units/fpu.scala:207:20, :211:20, :224:20, :242:8, :243:8, :244:8, src/main/scala/chisel3/util/Valid.scala:129:24, :130:26]
endmodule

