// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module RegisterReadDecode_1(
  input         io_iss_valid,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input  [6:0]  io_iss_uop_uopc,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input  [9:0]  io_iss_uop_fu_code,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input  [7:0]  io_iss_uop_br_mask,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input  [19:0] io_iss_uop_imm_packed,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input  [3:0]  io_iss_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input  [2:0]  io_iss_uop_ldq_idx,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_iss_uop_stq_idx,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input  [5:0]  io_iss_uop_pdst,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_iss_uop_prs1,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_iss_uop_prs2,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input  [4:0]  io_iss_uop_mem_cmd,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input  [1:0]  io_iss_uop_mem_size,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input         io_iss_uop_mem_signed,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_iss_uop_is_fence,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_iss_uop_is_amo,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_iss_uop_uses_ldq,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_iss_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input  [1:0]  io_iss_uop_lrs1_rtype,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_iss_uop_lrs2_rtype,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  input         io_iss_uop_fp_val,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output        io_rrd_valid,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output [6:0]  io_rrd_uop_uopc,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output [9:0]  io_rrd_uop_fu_code,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output        io_rrd_uop_ctrl_is_load,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_rrd_uop_ctrl_is_sta,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_rrd_uop_ctrl_is_std,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output [7:0]  io_rrd_uop_br_mask,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output [19:0] io_rrd_uop_imm_packed,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output [3:0]  io_rrd_uop_rob_idx,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output [2:0]  io_rrd_uop_ldq_idx,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_rrd_uop_stq_idx,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output [5:0]  io_rrd_uop_pdst,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_rrd_uop_prs1,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_rrd_uop_prs2,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output [4:0]  io_rrd_uop_mem_cmd,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output [1:0]  io_rrd_uop_mem_size,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output        io_rrd_uop_mem_signed,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_rrd_uop_is_fence,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_rrd_uop_is_amo,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_rrd_uop_uses_ldq,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_rrd_uop_uses_stq,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output [1:0]  io_rrd_uop_lrs1_rtype,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
                io_rrd_uop_lrs2_rtype,	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
  output        io_rrd_uop_fp_val	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:310:14]
);

  wire io_rrd_uop_ctrl_is_load_0 = io_iss_uop_uopc == 7'h1;	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:339:46]
  wire _io_rrd_uop_ctrl_is_sta_T_1 = io_iss_uop_uopc == 7'h43;	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:340:76]
  wire io_rrd_uop_ctrl_is_sta_0 = io_iss_uop_uopc == 7'h2 | _io_rrd_uop_ctrl_is_sta_T_1;	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:340:{46,57,76}]
  assign io_rrd_valid = io_iss_valid;
  assign io_rrd_uop_uopc = io_iss_uop_uopc;
  assign io_rrd_uop_fu_code = io_iss_uop_fu_code;
  assign io_rrd_uop_ctrl_is_load = io_rrd_uop_ctrl_is_load_0;	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:339:46]
  assign io_rrd_uop_ctrl_is_sta = io_rrd_uop_ctrl_is_sta_0;	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:340:57]
  assign io_rrd_uop_ctrl_is_std = io_iss_uop_uopc == 7'h3 | io_rrd_uop_ctrl_is_sta_0 & io_iss_uop_lrs2_rtype == 2'h0;	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:340:57, :341:{46,57,84,109}]
  assign io_rrd_uop_br_mask = io_iss_uop_br_mask;
  assign io_rrd_uop_imm_packed = _io_rrd_uop_ctrl_is_sta_T_1 | io_rrd_uop_ctrl_is_load_0 & io_iss_uop_mem_cmd == 5'h6 ? 20'h0 : io_iss_uop_imm_packed;	// @[generators/boom/src/main/scala/exu/register-read/func-unit-decode.scala:320:16, :339:46, :340:76, :343:{39,69,91,103}, :344:27]
  assign io_rrd_uop_rob_idx = io_iss_uop_rob_idx;
  assign io_rrd_uop_ldq_idx = io_iss_uop_ldq_idx;
  assign io_rrd_uop_stq_idx = io_iss_uop_stq_idx;
  assign io_rrd_uop_pdst = io_iss_uop_pdst;
  assign io_rrd_uop_prs1 = io_iss_uop_prs1;
  assign io_rrd_uop_prs2 = io_iss_uop_prs2;
  assign io_rrd_uop_mem_cmd = io_iss_uop_mem_cmd;
  assign io_rrd_uop_mem_size = io_iss_uop_mem_size;
  assign io_rrd_uop_mem_signed = io_iss_uop_mem_signed;
  assign io_rrd_uop_is_fence = io_iss_uop_is_fence;
  assign io_rrd_uop_is_amo = io_iss_uop_is_amo;
  assign io_rrd_uop_uses_ldq = io_iss_uop_uses_ldq;
  assign io_rrd_uop_uses_stq = io_iss_uop_uses_stq;
  assign io_rrd_uop_lrs1_rtype = io_iss_uop_lrs1_rtype;
  assign io_rrd_uop_lrs2_rtype = io_iss_uop_lrs2_rtype;
  assign io_rrd_uop_fp_val = io_iss_uop_fp_val;
endmodule

