// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module RegisterFileSynthesizable_2(
  input       clock,
              io_write_ports_0_valid,	// @[generators/boom/src/main/scala/exu/register-read/regfile.scala:83:14]
  input [5:0] io_write_ports_0_bits_addr	// @[generators/boom/src/main/scala/exu/register-read/regfile.scala:83:14]
);

  reg [5:0] read_addrs_0;	// @[generators/boom/src/main/scala/exu/register-read/regfile.scala:139:50]
  reg [5:0] read_addrs_1;	// @[generators/boom/src/main/scala/exu/register-read/regfile.scala:139:50]
  always @(posedge clock) begin
    read_addrs_0 <= 6'h0;	// @[generators/boom/src/main/scala/exu/register-read/regfile.scala:83:14, :139:50]
    read_addrs_1 <= 6'h0;	// @[generators/boom/src/main/scala/exu/register-read/regfile.scala:83:14, :139:50]
  end // always @(posedge)
endmodule

