// Generated by CIRCT unknown git version
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module RenameFreeList_1(
  input        clock,
               reset,
               io_reqs_0,	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:29:14]
  output       io_alloc_pregs_0_valid,	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:29:14]
  output [5:0] io_alloc_pregs_0_bits,	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:29:14]
  input        io_dealloc_pregs_0_valid,	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:29:14]
  input  [5:0] io_dealloc_pregs_0_bits,	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:29:14]
  input        io_ren_br_tags_0_valid,	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:29:14]
  input  [2:0] io_ren_br_tags_0_bits,	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:29:14]
               io_brupdate_b2_uop_br_tag,	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:29:14]
  input        io_brupdate_b2_mispredict,	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:29:14]
               io_debug_pipeline_empty	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:29:14]
);

  reg  [5:0]  r_sel;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:82:28]
  reg  [47:0] free_list;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:50:26]
  reg  [47:0] br_alloc_lists_0;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27]
  reg  [47:0] br_alloc_lists_1;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27]
  reg  [47:0] br_alloc_lists_2;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27]
  reg  [47:0] br_alloc_lists_3;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27]
  reg  [47:0] br_alloc_lists_4;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27]
  reg  [47:0] br_alloc_lists_5;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27]
  reg  [47:0] br_alloc_lists_6;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27]
  reg  [47:0] br_alloc_lists_7;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27]
  wire [47:0] sels_0 = free_list[0] ? 48'h1 : free_list[1] ? 48'h2 : free_list[2] ? 48'h4 : free_list[3] ? 48'h8 : free_list[4] ? 48'h10 : free_list[5] ? 48'h20 : free_list[6] ? 48'h40 : free_list[7] ? 48'h80 : free_list[8] ? 48'h100 : free_list[9] ? 48'h200 : free_list[10] ? 48'h400 : free_list[11] ? 48'h800 : free_list[12] ? 48'h1000 : free_list[13] ? 48'h2000 : free_list[14] ? 48'h4000 : free_list[15] ? 48'h8000 : free_list[16] ? 48'h10000 : free_list[17] ? 48'h20000 : free_list[18] ? 48'h40000 : free_list[19] ? 48'h80000 : free_list[20] ? 48'h100000 : free_list[21] ? 48'h200000 : free_list[22] ? 48'h400000 : free_list[23] ? 48'h800000 : free_list[24] ? 48'h1000000 : free_list[25] ? 48'h2000000 : free_list[26] ? 48'h4000000 : free_list[27] ? 48'h8000000 : free_list[28] ? 48'h10000000 : free_list[29] ? 48'h20000000 : free_list[30] ? 48'h40000000 : free_list[31] ? 48'h80000000 : free_list[32] ? 48'h100000000 : free_list[33] ? 48'h200000000 : free_list[34] ? 48'h400000000 : free_list[35] ? 48'h800000000 : free_list[36] ? 48'h1000000000 : free_list[37] ? 48'h2000000000 : free_list[38] ? 48'h4000000000 : free_list[39] ? 48'h8000000000 : free_list[40] ? 48'h10000000000 : free_list[41] ? 48'h20000000000 : free_list[42] ? 48'h40000000000 : free_list[43] ? 48'h80000000000 : free_list[44] ? 48'h100000000000 : free_list[45] ? 48'h200000000000 : free_list[46] ? 48'h400000000000 : {free_list[47], 47'h0};	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:50:{26,45}, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:85:71]
  wire [63:0] allocs_0 = 64'h1 << r_sel;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:82:28, src/main/scala/chisel3/util/OneHot.scala:58:35]
  reg  [47:0] casez_tmp;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:63:63]
  always @(*) begin	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:63:63]
    casez (io_brupdate_b2_uop_br_tag)	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:63:63]
      3'b000:
        casez_tmp = br_alloc_lists_0;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :63:63]
      3'b001:
        casez_tmp = br_alloc_lists_1;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :63:63]
      3'b010:
        casez_tmp = br_alloc_lists_2;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :63:63]
      3'b011:
        casez_tmp = br_alloc_lists_3;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :63:63]
      3'b100:
        casez_tmp = br_alloc_lists_4;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :63:63]
      3'b101:
        casez_tmp = br_alloc_lists_5;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :63:63]
      3'b110:
        casez_tmp = br_alloc_lists_6;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :63:63]
      default:
        casez_tmp = br_alloc_lists_7;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :63:63]
    endcase	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:63:63]
  end // always @(*)
  wire [47:0] br_deallocs = casez_tmp & {48{io_brupdate_b2_mispredict}};	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:63:{63,69}]
  wire [63:0] _dealloc_mask_T = 64'h1 << io_dealloc_pregs_0_bits;	// @[src/main/scala/chisel3/util/OneHot.scala:58:35]
  wire [47:0] dealloc_mask = _dealloc_mask_T[47:0] & {48{io_dealloc_pregs_0_valid}} | br_deallocs;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:63:63, :64:{64,79,85,110}, src/main/scala/chisel3/util/OneHot.scala:58:35]
  reg         r_valid;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:81:26]
  wire        sel_fire_0 = (~r_valid | io_reqs_0) & (|sels_0);	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:80:27, :81:26, :85:{21,30,45}, src/main/scala/chisel3/util/Mux.scala:50:70]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:94:10]
    wire [47:0] io_debug_freelist = free_list | allocs_0[47:0] & {48{r_valid}};	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:50:26, :59:88, :81:26, :91:{34,77,83}, src/main/scala/chisel3/util/OneHot.scala:58:35]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:94:10]
      if (~reset & (|(io_debug_freelist & dealloc_mask))) begin	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:64:110, :91:{34,77}, :94:{10,31,47}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:94:10]
          $error("Assertion failed: [freelist] Returning a free physical register.\n    at rename-freelist.scala:94 assert (!(io.debug.freelist & dealloc_mask).orR, \"[freelist] Returning a free physical register.\")\n");	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:94:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:94:10]
          $fatal;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:94:10]
      end
      if (~reset & ~(~io_debug_pipeline_empty | {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, io_debug_freelist[0]} + {1'h0, io_debug_freelist[1]} + {1'h0, io_debug_freelist[2]}} + {1'h0, {1'h0, io_debug_freelist[3]} + {1'h0, io_debug_freelist[4]} + {1'h0, io_debug_freelist[5]}}} + {1'h0, {1'h0, {1'h0, io_debug_freelist[6]} + {1'h0, io_debug_freelist[7]} + {1'h0, io_debug_freelist[8]}} + {1'h0, {1'h0, io_debug_freelist[9]} + {1'h0, io_debug_freelist[10]} + {1'h0, io_debug_freelist[11]}}}} + {1'h0, {1'h0, {1'h0, {1'h0, io_debug_freelist[12]} + {1'h0, io_debug_freelist[13]} + {1'h0, io_debug_freelist[14]}} + {1'h0, {1'h0, io_debug_freelist[15]} + {1'h0, io_debug_freelist[16]} + {1'h0, io_debug_freelist[17]}}} + {1'h0, {1'h0, {1'h0, io_debug_freelist[18]} + {1'h0, io_debug_freelist[19]} + {1'h0, io_debug_freelist[20]}} + {1'h0, {1'h0, io_debug_freelist[21]} + {1'h0, io_debug_freelist[22]} + {1'h0, io_debug_freelist[23]}}}}} + {1'h0, {1'h0, {1'h0, {1'h0, {1'h0, io_debug_freelist[24]} + {1'h0, io_debug_freelist[25]} + {1'h0, io_debug_freelist[26]}} + {1'h0, {1'h0, io_debug_freelist[27]} + {1'h0, io_debug_freelist[28]} + {1'h0, io_debug_freelist[29]}}} + {1'h0, {1'h0, {1'h0, io_debug_freelist[30]} + {1'h0, io_debug_freelist[31]} + {1'h0, io_debug_freelist[32]}} + {1'h0, {1'h0, io_debug_freelist[33]} + {1'h0, io_debug_freelist[34]} + {1'h0, io_debug_freelist[35]}}}} + {1'h0, {1'h0, {1'h0, {1'h0, io_debug_freelist[36]} + {1'h0, io_debug_freelist[37]} + {1'h0, io_debug_freelist[38]}} + {1'h0, {1'h0, io_debug_freelist[39]} + {1'h0, io_debug_freelist[40]} + {1'h0, io_debug_freelist[41]}}} + {1'h0, {1'h0, {1'h0, io_debug_freelist[42]} + {1'h0, io_debug_freelist[43]} + {1'h0, io_debug_freelist[44]}} + {1'h0, {1'h0, io_debug_freelist[45]} + {1'h0, io_debug_freelist[46]} + {1'h0, io_debug_freelist[47]}}}}} > 6'hE)) begin	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :91:{34,77}, :94:10, :95:{10,11,36,47,67}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:95:10]
          $error("Assertion failed: [freelist] Leaking physical registers.\n    at rename-freelist.scala:95 assert (!io.debug.pipeline_empty || PopCount(io.debug.freelist) >= (numPregs - numLregs - 1).U,\n");	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:95:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:95:10]
          $fatal;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:95:10]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [30:0] _r_sel_T_1 = {16'h0, sels_0[47:33]} | sels_0[31:1];	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:72:73, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:31:18, :32:28]
  wire [14:0] _r_sel_T_3 = _r_sel_T_1[30:16] | _r_sel_T_1[14:0];	// @[src/main/scala/chisel3/util/OneHot.scala:30:18, :31:18, :32:28]
  wire [6:0]  _r_sel_T_5 = _r_sel_T_3[14:8] | _r_sel_T_3[6:0];	// @[src/main/scala/chisel3/util/OneHot.scala:30:18, :31:18, :32:28]
  wire [2:0]  _r_sel_T_7 = _r_sel_T_5[6:4] | _r_sel_T_5[2:0];	// @[src/main/scala/chisel3/util/OneHot.scala:30:18, :31:18, :32:28]
  wire [47:0] _GEN = allocs_0[47:0] & {48{io_reqs_0}};	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:59:{88,94}, src/main/scala/chisel3/util/OneHot.scala:58:35]
  always @(posedge clock) begin
    if (reset) begin
      free_list <= 48'hFFFFFFFFFFFE;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:50:{26,45}]
      r_valid <= 1'h0;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :81:26]
    end
    else begin
      free_list <= (free_list & ~(sels_0 & {48{sel_fire_0}}) | dealloc_mask) & 48'hFFFFFFFFFFFE;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:50:{26,45}, :62:{60,66}, :64:110, :76:{27,29,39,55}, :85:45, src/main/scala/chisel3/util/Mux.scala:50:70]
      r_valid <= r_valid & ~io_reqs_0 | (|sels_0);	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:80:27, :81:26, :84:{24,27,39}, src/main/scala/chisel3/util/Mux.scala:50:70]
    end
    br_alloc_lists_0 <= io_ren_br_tags_0_bits == 3'h0 & io_ren_br_tags_0_valid ? 48'h0 : br_alloc_lists_0 & ~br_deallocs | _GEN;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :59:88, :63:63, :69:{72,85}, :71:29, :72:{58,60,73}, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:58:35]
    br_alloc_lists_1 <= io_ren_br_tags_0_bits == 3'h1 & io_ren_br_tags_0_valid ? 48'h0 : br_alloc_lists_1 & ~br_deallocs | _GEN;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :59:88, :63:63, :69:{72,85}, :71:29, :72:{58,60,73}, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:58:35]
    br_alloc_lists_2 <= io_ren_br_tags_0_bits == 3'h2 & io_ren_br_tags_0_valid ? 48'h0 : br_alloc_lists_2 & ~br_deallocs | _GEN;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :59:88, :63:63, :69:{72,85}, :71:29, :72:{58,60,73}, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:58:35]
    br_alloc_lists_3 <= io_ren_br_tags_0_bits == 3'h3 & io_ren_br_tags_0_valid ? 48'h0 : br_alloc_lists_3 & ~br_deallocs | _GEN;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :59:88, :63:63, :69:{72,85}, :71:29, :72:{58,60,73}, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:58:35]
    br_alloc_lists_4 <= io_ren_br_tags_0_bits == 3'h4 & io_ren_br_tags_0_valid ? 48'h0 : br_alloc_lists_4 & ~br_deallocs | _GEN;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :59:88, :63:63, :69:{72,85}, :71:29, :72:{58,60,73}, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:58:35]
    br_alloc_lists_5 <= io_ren_br_tags_0_bits == 3'h5 & io_ren_br_tags_0_valid ? 48'h0 : br_alloc_lists_5 & ~br_deallocs | _GEN;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :59:88, :63:63, :69:{72,85}, :71:29, :72:{58,60,73}, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:58:35]
    br_alloc_lists_6 <= io_ren_br_tags_0_bits == 3'h6 & io_ren_br_tags_0_valid ? 48'h0 : br_alloc_lists_6 & ~br_deallocs | _GEN;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :59:88, :63:63, :69:{72,85}, :71:29, :72:{58,60,73}, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:58:35]
    br_alloc_lists_7 <= (&io_ren_br_tags_0_bits) & io_ren_br_tags_0_valid ? 48'h0 : br_alloc_lists_7 & ~br_deallocs | _GEN;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:51:27, :59:88, :63:63, :69:{72,85}, :71:29, :72:{58,60,73}, src/main/scala/chisel3/util/Mux.scala:50:70]
    if (sel_fire_0)	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:85:45]
      r_sel <= {|(sels_0[47:32]), |(_r_sel_T_1[30:15]), |(_r_sel_T_3[14:7]), |(_r_sel_T_5[6:3]), |(_r_sel_T_7[2:1]), _r_sel_T_7[2] | _r_sel_T_7[0]};	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:82:28, src/main/scala/chisel3/util/Mux.scala:50:70, src/main/scala/chisel3/util/OneHot.scala:30:18, :31:18, :32:{10,14,28}]
  end // always @(posedge)
  assign io_alloc_pregs_0_valid = r_valid;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:81:26]
  assign io_alloc_pregs_0_bits = r_sel;	// @[generators/boom/src/main/scala/exu/rename/rename-freelist.scala:82:28]
endmodule

